### ISSUE TITLE
Chybějící čísla

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#111]
Ve výpisu chybějících čísel vyvolaném ikonkou "i" se jako chybějící čísla vypisují čísla, která vůbec nechybí. Při generování svazku například vynecháme neděle, protože titul v neděli nevycházel, přesto se všechny neděle zobrazí jako chybějící čísla. Navíc s čísly výtisků, která mají vydání pondělní.

**Comment by albertoh** [comment]
Opraveno.
Ale pozor, nektere zaznamy maji stav "chybejci stranky" ale nemaji informaci o tech strankach. Ikonka se zobrazuje podle pole stav.

**Comment by korhon** [comment]
Zdá se, že chybějící čísla už se zobrazují správně, zato se ale problém přesunul do položky "Poškozená čísla", kde se opět ukazuje seznam těch, která vůbec poškozená nejsou.

**Comment by holecInqool** [comment]
Dobrý deň,   
  
poprosil by som o inštruktáž, ako dokážem problém zreplikovať.   
Ako sa dostanem ku ikonke "i" a kde budem vidieť informáciu o Poškozených číslech?   
  
Poprosím ideálne o návod, ako sa dostanem k tomu, že uvidím chybu tak, ako ju prezentujete.   
URL odkazy prípadne screenshoty určite pomôžu.   
  
Aby som prípadne nemusel otravovať s na pohľad triviálnymi vecami - neexistuje prosím nejaká užívateľská dokumentácia, ktorá by prezentovala základné funkcionality systému?

**Comment by AnnaCajthamlova** [comment]
@korhon Miloši prosím o komentář p. Holcovi

**Comment by korhon** [comment]
Ikona "i" Přehled svazku je zařazena vedle tlačítka pro zobrazení tabulky v “Editaci vstupních dat”. V přehledu svazku se v podobě náhledu promítne souhrn dat uložených z tabulky “Detailní popis exempláře”. Na první pohled je tak patrný celkový stav popisovaného svazku, míra poškození a informace o kompletnosti exempláře. 
![obrazek](https://user-images.githubusercontent.com/33937374/182873737-4505586b-a45f-4597-bcfd-1a881e63682f.png)

Na stejný přehled svazku se dostanu kliknutím na čárový kód v tabulce přehled exemplářů
![obrazek](https://user-images.githubusercontent.com/33937374/182873333-2bfeac08-4fbc-4248-aebf-8aa72de04484.png)

**Comment by Kretiss** [comment]
@korhon @zabak Nasazeno na testu, prosím o kontrolu

**Comment by zabak** [comment]
@korhon prosím o otestování

**Comment by ludvicekj** [comment]
myslím, že nic navíc už neukazuje.. 
zaškrtnutý checkbox "Poškozené strany" se v Přehledu ukáže jako Poškozená čísla. ostatní chyby se ukážou pouze počtem, ne v jakých číslech to je.

**Comment by zabak** [comment]
@korhon prosím o otestování na produkci

**Comment by Kretiss** [comment]
@korhon Můžu poprosit o screeny obrazovky? Navíc, stav chybí číslo se mazal v https://github.com/NLCR/evidence.periodik/issues/161

**Comment by korhon** [comment]
![snimek 01](https://user-images.githubusercontent.com/33937374/201037007-73eb3e6a-8e63-4850-bef6-22627d938bc2.jpg)

**Comment by korhon** [comment]
![snimek 02](https://user-images.githubusercontent.com/33937374/201037078-5a54a9b9-a2c7-4a0e-acee-57c8374425e4.jpg)

**Comment by zabak** [comment]
@korhon připomínám

**Comment by korhon** [comment]
Pořád to není ono. 
U svazku ČK  2650552177
https://permonik.inqool.cz/permonik/svazek/2650552177
se jako chybějící číslo ukazuje pondělí 27.3.
![obrazek](https://user-images.githubusercontent.com/33937374/211806841-7b06050d-8e05-463e-ac2a-9fa3c0e6bb40.png)

Ale tam žádné číslo nechybí, jak je vidět z číselné řady, která běží dál. Nejspíš byly velikonoce. 
Zjednodušeně to, že číslo chybí, se nemá brát z data, ale chybějícího čísla v číselné řadě. 

Další případ je ČK 314800329591 
https://permonik.inqool.cz/permonik/svazek/314800329591

![obrazek](https://user-images.githubusercontent.com/33937374/211808676-487303b0-f779-43b1-b576-0e14dc098b9a.png)

Ty chybějící čísla v květnu jsou asi v pořádku, ale toho 17.3. chybí jenom na první pohled, protože obvyklé úterní číslo vyšlo zjevně v pondělí. Nejspíš zase kvůli velikoncům. V řadě čísel nechybí jenom 41, 42 a 43, což jsou ty tři dny v květnu.

![obrazek](https://user-images.githubusercontent.com/33937374/211810168-094882e9-67ff-4b0b-a3b2-31cb8ef8f5d0.png)

**Comment by Kretiss** [comment]
@korhon @zabak Toto issue se může uzavřít v prospěch issue https://github.com/NLCR/evidence.periodik/issues/216?
