### ISSUE TITLE
stav "kompletní" v editaci svazku

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#116]
přes Editaci svazku nelze označit číslo jako kompletní. lze pouze označit různé poškození a pokud se nic nezatrhne zůstane číslo s ikonkou "neprohlédnuto".

![stav kompletní](https://user-images.githubusercontent.com/40558551/85520570-61314f00-b603-11ea-9f82-dfcfad1a5e3a.png)

**Comment by ludvicekj** [comment]
související problém je ještě tento: pokud se jednotlivá čísla uloží jako kompletní jinde, ale potom se znovu otevřou a uloží pomocí Editace svazku stav "kompletní" zmizí.

**Comment by albertoh** [comment]
To asi znamena pridat novy stav (checkbox) do seznamu stavu. Je to tak?

**Comment by korhon** [comment]
To není potřeba. Kompletní je to v případě, že nezaškrtnu žádný z checkboxů.

**Comment by albertoh** [comment]
Nakonec pridal jsem sloupec, aby se dalo rozlisit kdyz je nove vlozen zaznam (zadny stav), a revidovano s oznacenim "klompetni"

**Comment by korhon** [comment]
To mi nepřipadá šikovné. Pokud fyzicky projdu svazek a nezaškrtnu žádné defekty, pak je prostě kompletní a nechci tuto skutečnost u každého čísla potvrzovat. Nedalo by se to nahradit jedním tlačítkem pro celou stránku editace svazku? Např. "Stav ověřen" nebo tak nějak...

**Comment by zabak** [comment]
Jestli to dobře chápu, tak ten sloupec "kompletní" má smysl, ale měl by se jmenovat "prohlédnuto". A měla by být možnost ho zatrhnout hromadně pro celý svazek.

**Comment by ludvicekj** [comment]
samostatný sloupec má podle mě smysl. jak se bude jmenovat je nakonec asi jedno. nemyslím, že je problém u každého čísla zaškrtnout, naopak tak jako tak se musí zkontrolovat několik údajů (číslo, počet stran, ..) a to odškrtnutí mi přijde jako dobrý krok k dalšímu číslu..

**Comment by korhon** [comment]
Takže navážeme na předchozí debatu. Tento sloupec smysl nemá a měl by z tabulky zmizet. Místo něj by mělo na konci stránky být tlačítko "Prohlédnuto" nebo "Zkontrolováno" nebo "Ověřeno"

**Comment by Kretiss** [comment]
@zabak @korhon Je tohle finální verdikt?

**Comment by korhon** [comment]
Z mého pohledu a po opakované diskusi je to finální verdikt

**Comment by zabak** [comment]
@korhon jsem pro Ověřeno, protože je to nejkratší slovo. To tlašítko je myšleno pro celý svazek, jak se o tom diskutovalo výše, že?

**Comment by zabak** [comment]
Platí "Ověřeno"

**Comment by Kretiss** [comment]
@zabak Nasazeno na našem testu. Po stisknutí tlačítka se automaticky uloží celý svazek a pro vyplněné exempláře se zatrhne stav **Oveřeno**. K tomu mám poznámku...sloupec Ověřeno bych tam nechal, protože když se to jednou zaklikne pro celý svazek a náhodou se bude chtít něco změnit, nebude možnost jak tuhle změnu rozumně vrátit.

**Comment by ludvicekj** [comment]
sloupec i tlačítko, myslím, funguje dobře. 

ale asi k projednání na schůzce: "ověřeno" přepíše ostatní typy ikonek, je tedy otázka do budoucna týkající se ještě těch dalších ikonek, které tam byly kdysi dávno přidány pro ulehčení přehledu, zda je tam stále chceme mít.. viz příklad na obrázku
![ikonky stavu](https://user-images.githubusercontent.com/40558551/192549831-b4b346f7-9283-4856-a56b-c429ba305f1d.png)

**Comment by zabak** [comment]
@ludvicekj prosím založit jako nové issue - stávající funkcionalita bude nasazena na produkci.

**Comment by ludvicekj** [comment]
funguje, zavírám
