### ISSUE TITLE
Co má dělat menu v kalendáři?

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#123]
![image](https://user-images.githubusercontent.com/811537/85959647-e323ce00-b99d-11ea-8ee3-eaeccaf084b1.png)

Ani jedna z voleb nic nedělá, když na ni kliknu. Navrhuji toto menu zrušit, protože je matoucí - nebo musí být jasný use-case.

**Comment by zabak** [comment]
Smazat všechny mutace v tomto zobrazení je velmi nebezpečná akce, sem nepatří. Přiřadit pozadí - čemu? Přidat exemplář - nedává smysl, když nevím, které exempláře tam už jsou.

**Comment by albertoh** [comment]
Toto je pozustatek. Byl to navhr, co muzeme tam delat. Odstranim

**Comment by zabak** [comment]
menu odstraněno

**Comment by zabak** [comment]
Pokud si v kalendáři rozkliknu "x dalších vydání", dostanu se na zobrazení kalendáře, kde jsou dny pod sebou a kde to menu nebylo odstraněno. Prosím o odstranění menu i zde

**Comment by zabak** [comment]
@Kretiss předpokládám, že bylo zavřeno omylem, oprava není nasazena ani na testu

**Comment by Kretiss** [comment]
@zabak Nasazeno na našem testu. Zavřel jsem to na základě diskuze v jiném issue, kde jsme se bavili, že tu stránku nebudeme používat. Upravil jsem to ale i tak, takže přes odkaz to můžete zkontrolovat.

**Comment by zabak** [comment]
@Kretiss akorát ten odkaz nemám, takže to zkontrolovat nemůžu. Ale mezitím jsme se rozhodli, že se celá ta stránka odstraní, to máte pravdu. Měli bychom ji ale tím pádem odstranit i z kódu, ať se zmenší jeho velikost. Nebo je nějaký důvod to tam nechávat?

**Comment by Kretiss** [comment]
@zabak stačí v url adrese přepsat month na list, viz https://permonik.inqool.cz/permonik/calendar/2081c9cc60d1101b53c4a0ce348195ee/list/19660103. Prozatím to tam je, ale když zakomentuju importy, nebude to zakomponované ve výsledném balíčku nasazovaném na server. Nechal bych to tam, kdyby se časem přišlo na nějaký způsob, jak to dobře využít. Můžeme to potom ale smazat.

**Comment by zabak** [comment]
může se nasadit.

**Comment by zabak** [comment]
resp. nenasadit, protože jsme řekli že to na serveru být nemá a nemělo by to vlastně zbytečně strašit v kódu.
