### ISSUE TITLE
v zobrazení kalendáře nefungují fasety

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#124]
Pokud mám titul zobrazený jako kalendář, tak systém ignoruje klikání na fasety. Navíc není možné zobrazit všechny položky v rámci dne. Vzhledem k #123 navrhuji toto zobrazení zcela zrušit, pokud nepřijdeme na to, jak v něm zobrazit potřebné informace a nebude jasný use-case.

![image](https://user-images.githubusercontent.com/811537/85959833-17e45500-b99f-11ea-9f8e-71d2659da134.png)

**Comment by zabak** [comment]
Kdyby fungovaly fasety a bylo vidět všechny řádky v rámci dne, tak by to bylo ideální pro kontrolu. Pak už zbývá jen dořešit #123

**Comment by albertoh** [comment]
Facety bych tady schoval. Kalendar je vazan na metatitul

**Comment by zabak** [comment]
@Foltom @korhon prosím zamyslete se nad tímto víc. To co navrhuje Alberto sice řeší problém, ale pokud se #123 vyřeší odstraněním menu a tady se odstraní fasety, tak ten kalendář nebude k ničemu, protože se nezobrazí ke každému dni všechno. Potřebujeme pak ale takový kalendář?

**Comment by zabak** [comment]
V Chrome se nezobrazuje info typu "2 další vydání", zatímco v Opeře to funguje

**Comment by korhon** [comment]
![kalendar](https://user-images.githubusercontent.com/33937374/90636018-4c9bbc80-e22a-11ea-9fc8-b506ea4ff1b9.png)

**Comment by zabak** [comment]
![image](https://user-images.githubusercontent.com/811537/90636145-7c4ac480-e22a-11ea-939c-18266124656c.png)
takhle to vypadá v Chrome

**Comment by korhon** [comment]
Odkaz "2 další vydání" nic neukazuje...

**Comment by zabak** [comment]
Bylo by myslím lepší, kdyby kalendář neměl fixní výšku řádků ale řádky byly vysoké tak, aby se tem vešla všechna vydání. Zároveň prosím o vysvětlení, co znamenají barvy položek v kalendáři (resp. podle jakých pravidel se obarvuje) a podle jakých pravidel se vytvářejí samostatné řádky.

**Comment by zabak** [comment]
@Kretiss teď se mi v kalendáři nezobrazuje nic - testováno na https://permonik.inqool.cz/permonik/calendar/2081c9cc60d1101b53c4a0ce348195ee/month/19530101

**Comment by Kretiss** [comment]
@zabak To se mi tak zobrazovalo taky a popravdě momentálně nevím, proč tomu tak je.. ale tady to vidět jde https://permonik.inqool.cz/permonik/calendar/2081c9cc60d1101b53c4a0ce348195ee/month/19660120

**Comment by zabak** [comment]
Aha, tady vidím problém - netušil jsem, že je tam prolink na x dalších vydání a jiná forma zobrazení. Osobně bych preferoval, aby se v tom kalendáři ve formě tabulky (1 týden 1 řádek) zobrazily všechna vydání (aby se výška řádku přizpůsobila). Ta forma zobrazení s každým dnem na novém řádku mi připadá nadbytečná a nepřehledná. Prosím o vyjádření alespoň @korhon a @BrozekAles

**Comment by zabak** [comment]
Znovu jsem otevřel #123 ale pokud bychom se rozhodli zrušit tu stránku kde je jeden den na řádku, tak se to #123 může zase zavřít.

**Comment by BrozekAles** [comment]
Kalendář ve formě tabulky nevyužívám, resp. jsem ani o něm dosud nevěděl, a když se na to teď dívám, tak ani nechápu, co lze z kalendáře ve formě tabulky vyčíst, co znamenají barvy položek apod.

**Comment by zabak** [comment]
@BrozekAles barvy jsou vysvětlené zde: https://github.com/NLCR/evidence.periodik/issues/124#issuecomment-1235496911 - myslím, že po úpravě zobrazení by to kalendářové zobrazení mohlo být vhodným výchozím zobrazením pro uživatele. Kdyby tam byla vidět všechna ten den vyšlá vydání s možností rozkliknout si kde dané vydání mají a další detaily, tak vlastně nepotřebujeme nic víc.

**Comment by BrozekAles** [comment]
Aha, zmátl mne ten výraz issues, který užívám jen pro issues na Githubu :-)  Takže zelená barva značí, že daný výtisk je O.K. :-)

**Comment by Kretiss** [comment]
@BrozekAles @korhon @zabak Jaké je teda finální vyjádření? Ať s tím issue nějak pohnem. Viděl bych to tak, že se všechny vydání zobrazí v tom kalendáři a ten prolink na další vydání se zruší. Svým způsobem je to taková zbytečná duplikace. Funkcionalitu tam můžeme nechat, kdyby se v budoucnu něco změnilo.

**Comment by korhon** [comment]
Mně připadá kalendář velmi smysluplný, proklik na další vydání nevidím jako potřebný. Podle mě by to mělo fungovat tak, že se přímo v kalendáři vypíší všechna dostupná vydání včetně zobrazení symbolů mutačních vydání. 
V tom barevném řádku by potom byla informace ve tvaru:
číslo vydání - mutace - značky mutačních vydání - počet exemplářů. 
Např. 
3 Praha * 2
3 Praha ** 1
3 Ostrava 3
3 Ostrava *** 1
3 Brno * 3
atd. 
Pak by to bylo zdaleka nejpřehlednější zobrazenáí informace o tom, kolik je toho dochováno. 
Kam by měl vést proklik z těchto řádků, to zatím nevím. Mohlo by se zobrazit okno, kde se zobrazí čárové kódy exemplářů (pokud je jich víc) a pak proklik do tabulky editace svazku.

**Comment by BrozekAles** [comment]
Mně připadá kalendář také velmi smysluplný a připojuji se k názoru kol. Korhoně. Jen mi připomněla jeho zmínka o čárových kódech exemplářů, že - snad se nepletu - nelze zatím podle čárových kódů vyhledávat a při opravách a běžném prohlížení dosavadních výsledků naší práce by pomohlo, kdybychom nemuseli hledat jen podle let a vlastníka, ale i podle čárového kódu.

**Comment by zabak** [comment]
@BrozekAles pokud není na to vyhledávání založené issue, tak ho prosím založte.
@Kretiss udělejte to dle vašeho návrhu, textaci a linkování dle toho co píše @korhon

**Comment by Kretiss** [comment]
@zabak @korhon @BrozekAles Nasadil jsem na náš test, prosím o kontrolu, jestli to může být tak jak to je. Mám ale dotaz k těm datům. Ty exempláře byly vždycky vidět hned po tom, co se vytvořil nějaký svazek a exempláře se vyplnily? Příjde mi totiž, jak kdyby se to předtím ukládalo ještě dodatečně, aby to šlo v kalendáři vidět, protože se data vytahují z databáze **issue**, ale mnou vytvořený nový metatiul, včetně svazku a exemplářů je uložený jinak, v **issue** ho nenajdu. Poslední záznam z **issue** je 10. 8. 2020, a to Lidové noviny - Vydání Brno. Neměli se kolem tohoto data nějaká funkcionalita?

**Comment by zabak** [comment]
@Kretiss Je to divné - Když se podívám na LN na tom linku, tak to něco zobrazuje, ale na hlavní stránce to zobrazuje, že Lidové noviny mají 0 exemplářů. Vypadá to na nějakou nekonzistenci dat. Je tam i nekonzistence druhým směrem: Československý sport: Když ho rozkliknu z hlavní stránky, tak se mi zobrazí výpis čísel, ale tam když kliknu na datum, tak kalendář (rok 1953) se zobrazí prázdný. Rok 1966 tam ale je. 

Mimo to pár věcí:

- [ ] zobrazení v kalendáři přestalo deduplikovat. Pokud mám identické řádky, měl by být zobrazen jen jeden se dvojkou na konci. Identické je myšleno i co se barvy týče, takže v přiloženém příkladu by se sloučily jen řádky
 1,2 a 4. Po kliknutí na takový řádek uživatel uvidí, kde se daná čísla nacházejí a případně si některé rozklikne. <img width="208" alt="image" src="https://user-images.githubusercontent.com/811537/190929507-bf3f18a8-8ad5-4acd-a00b-7f307c12f246.png">
- [ ] Z důvodu přehlednosti by měly být řádky v kalendáři řazeny podle abecedy, aby nebylo promíchané Brno a Praha navzájem
- [ ] ČS sport, 3.1.1966 - první řádek nemá žádné čislo a je zelený - to je divné, očekával bych že tam bude číslo, když je tam ten řádek. Je to chyba v datech?
- [ ] Domluvili jsme se, že zobrazení kalendáře v podobě seznamu odstraníme - je proto potřeba odstranit i jeho ikonu z menu v kalendáři (prostřední ikona) - 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/811537/190929859-dcc71de8-1222-4c2c-9307-1cdc14855f26.png">

- [ ]  V menu výše je tlačítko na přechod do přehledu exemplářů. V menu v přehledu exemplářů ale není tlačítko na zobrazení kalendáře (to by mělo přejít na měsíc ve kterém je vydaný první exemplář ze zobrazeného seznamu
- [ ] Týden musí začínat pondělkem - teď je to tak, že když přejdu na další týden a ten začíná středou, tak prostě daný řádek začíná středou.

**Comment by zabak** [comment]
Mělo by být v nové verzi

**Comment by Kretiss** [comment]
@zabak @korhon @AnnaCajthamlova potřeboval bych přesně specifikovat, co má být v novém kalendáři zobrazeno v modálu po kliknutí na daný řádek dne (např řádek, ve kterém jsou 2 exempláře).

Momentálně mám nachystané takové okno: 
<img width="1677" alt="obrazek" src="https://github.com/NLCR/evidence.periodik/assets/74928322/a2880c57-3b01-425f-a398-d14b658e71aa">

Co dále tam teda má být?
- Odkaz na katalog (jaký?), odkaz na digitalizát  -> potřebuji dodat url adresy
- Přehled svazku, tak jak je tomu ve stávajícím permoníkovi, ale pro každý exemplář (svazek) zvlášť? Viz: 
<img width="673" alt="obrazek" src="https://github.com/NLCR/evidence.periodik/assets/74928322/630fad4d-ce7e-4a66-b315-c69af7a431bf">

**Comment by annavandasova** [comment]
Ano souhlasím s @zabak a prosím ještě o vyjádření i J. Ludvíčka

**Comment by Kretiss** [comment]
@zabak Můžu poprosit o ten link na knihovny.cz? Zkoušel jsem to jejich hledání např takhle: https://www.knihovny.cz/Search/Results?lookfor=314800329591&type=AllFields&limit=20, ale nic mi to nenajde

**Comment by annavandasova** [comment]
@zabak ověřit propojení na knihovny.cz

**Comment by zabak** [comment]
prověřím

**Comment by Kretiss** [comment]
@zabak Zavírám toto issue, protože nabylo a řeší se v něm hodně věcí najednou. Zůstává prověřit link na knihovny.cz, založím na to nové issue.
