### ISSUE TITLE
přečíslování svazku

### ISSUE THREAD

**Issue by Chlupova** [NLCR/evidence.periodik#140]
Jak přečísluji svazek, když nevyšlo Velikonoční pondělí a potřebuji přečíslovat vše od tohoto data ostatní až do konce svazku?
Když opravím formulář od tohoto data a uložím, tak se mi předchozí ztratí

Čs.sport -Brno i Praha Po 11.4.

**Comment by zabak** [comment]
12.4. bylo úterý po velikonocích a vyšlo číslo 85. To jsme upravili ručně. Nemáme ale způsob, jak přečíslovat zbytek čísel do konce svazku.

![image](https://user-images.githubusercontent.com/811537/90499238-9791d300-e149-11ea-924a-88e1368e5caf.png)

**Comment by zabak** [comment]
toto je specifikováno v #87

**Comment by albertoh** [comment]
Pridal jsem tlacitka pro precislovani. Otestujte, jestli tak staci

**Comment by korhon** [comment]
Nerozumím jak to funguje. Jednak to bude potřeba lépe počeštit :), ale hlavně jsem nepřišel na to, jak funguje "Automatické přečíslování na horu". 
Znamená to, že se posunuje číslování nahoru (o jedno číslo výš) nebo že se přečíslují čísla nad polem, kde změnu zadávám?
Zdá se mi, že uspokojivě funguje tehdy, když přepíšu číslo a zadám "Automatické přečíslování na dolu". Pak se všechny další čísla (níž v tabulce) o jedno změní. To by možná stačilo, ale i tak mě zajímá, jak jinak to má ještě fungovat...

**Comment by ludvicekj** [comment]
"nahoru" mi vrátilo číselnou řasu do původní podoby a také to nevidím jako úplně důležité.
"dolu" funguje dobře a jak má.

**Comment by AnnaCajthamlova** [comment]
ponechat pouze přečíslování dolů

**Comment by zabak** [comment]
K tomu dotaz: kde v kódu se tento text nachází? Fulltextově se mi ho nepodařilo najít.

**Comment by AnnaCajthamlova** [comment]
respektive teď je tam "automatické přečíslování na dolu"

**Comment by holecInqool** [comment]
Prosím o upresnenie čo je potrebné ešte dokončiť.   
  
\-Odstrániť "Automatické přečíslování nahoru"?   
\-Zmeniť názov z "Automatické přečíslování na dolu" na "Přečíslování dolů"?   
  
Je to všetko?

**Comment by zabak** [comment]
@holecInqool  Ano, jak to pročítám, tak to by mělo být všechno.

**Comment by annavandasova** [comment]
podle mě je to ok, co @zabak ?

**Comment by zabak** [comment]
ano funguje a dělá to to co to dělat má. Z hlediska UX se to chová divně, ale na to založím nové issue.
