### ISSUE TITLE
Editace vlastníků

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#145]
Jak je možno zadat nového vlastníka (knihovnu)? Neměla by tato funkce být doplněna?

**Comment by albertoh** [comment]
Tato moznost existuje v konfiguracnich souboru. Muzu pridat rozhrani pro administratora ve sprave.
Vyjadrete se, prosim.

**Comment by zabak** [comment]
Tohle musí říct @Foltom

**Comment by AnnaCajthamlova** [comment]
administrátor může přidat nového uživatele + nového vlastníka

**Comment by AnnaCajthamlova** [comment]
Informace o vlastnících:
název - zkratka - sigla

**Comment by zabak** [comment]
viz též. #158

**Comment by AnnaCajthamlova** [comment]
Administrátor má mít možnost přidat nového vlastníka. 
Set vlastníků ve struktuře název - zkratka - sigla. Ověřit jak je to v systému nyní @holecInqool 
(Nový uživatel nebude mít přiřazeného vlastníka, přidělí administrátor ze seznamu vlastníků.)

**Comment by zabak** [comment]
@Kretiss prosím o doplnění informace jak je to v systému nyní

**Comment by Kretiss** [comment]
@zabak Teď je to v systému tak, že jsou vlastníci pevně definovaní v konfiguračním souboru, viz screen 
<img width="309" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/191940719-e83b1315-b785-4a2f-b979-f1fbe6ae12de.png">

**Comment by zabak** [comment]
URL k ničemu není, evidentně nebylo nikdy potřeba. Zkratka se používá, sigla bude potřeba pro případnou konstrukci linku do adresáře knihoven nebo k dalším účelům, celý název knihovny může být použit jednak při přiřazování uživatelů do institucí nebo jako alt text nad zkratkou instituce.

**Comment by zabak** [comment]
stačí až do nové verze

**Comment by zabak** [comment]
Doplnit zkratku k zobrazení separátně od identifikátoru. Nové identifikátory budou:
NKP = ABA001
MZK = BOA001
VKOL=OLA001
SVKUL=ULG001
