### ISSUE TITLE
Možnost smazat celý svazek

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#149]
Navrhujeme zvážit, jestli by měla existovat možnost smazat celý svazek. Po vygenerování omylem nebo chybně se musí složitě mazat jednotlivé položky každá zvlášť.

**Comment by korhon** [comment]
![image](https://user-images.githubusercontent.com/33937374/95194466-9ab65080-07d5-11eb-9c85-cbaf5b9a1adc.png)

**Comment by AnnaCajthamlova** [comment]
před smazáním - kontrolní otázka

**Comment by BrozekAles** [comment]
a prosím přednostně vyřešit toto issue, protože je klíčové pro čištění chyb v datech již uložených svazků, resp. pro testování účinnosti oprav issues

**Comment by zabak** [comment]
Kontrolní otázka bude dvojitá:
Opravdu chcete smazat celý svazek? Ano/Ne (default Ne)
Druhá kontrolní otázka
Nechcete si to ještě rozmyslet? Ano/Ne (default Ano)

**Comment by Kretiss** [comment]
@zabak Mám to navržené, ale potřebuju si ověřit jednu informaci. Platí to, že je jenom jeden svazek pro daný čárový kód u jednoho vlastníka? Tzn., může nastat, že jsou exempláře třeba od 1.1. 1930 do 1.5.1930 a dva svazky, jeden od 1.1 do 28.2 a druhý od 1.3 do 31.5. pod stejným čárovým kódem a knihovnou?

Momentálně to totiž funguje tak, že pokud se vytvoří druhý svazek s jiným rozsahem datumů, přeuloží se ten původní co tam byl, takže exempláře co byly v tom původním svazku jakoby nikam nepatří, pokud jsou mimo nové datum.. takže se při mazání ani nesmažou, ALE zůstanou v přehledové tabulce (adresa .../result/...)

**Comment by Kretiss** [comment]
@zabak Nahrál jsem to na náš test, můžete to chování vyzkoušet.

**Comment by zabak** [comment]
Čárový kód je unikátní identifikátor svazku (teoreticky v rámci českých knihoven, ale zcela jistě v rámci instituce). Z hlediska Permonika i kdyby měly dva svazky stejný čárový kód (nalepený třeba na krabici s těmito dvěma svazky), tak Permonik to nemá jak poznat a bral by to jako jeden svazek.

**Comment by BrozekAles** [comment]
Posílám printscreen chybové hlášky při užití funkce smazat celý svazek. 
![Snímek obrazovky 2022-09-25 v 11 35 47](https://user-images.githubusercontent.com/7532753/192137778-a26dcdcd-71a0-4aee-bda4-8d605a3a58a5.png)

K této hlášce došlo, když jsem při detailním popisování svazku udělal chybu: omylem jsem přiřadil přílohu Volno k jinému dni a chtěl se zbavit té chyby tak, že jsem použil tlačítko Zrušit změny. Tím ale zmizely údaje z editace vstupních dat (zůstal tam jen metatitul a vlastník, což je fajn, první číslo jako 0 a posl. číslo "-1". Po znovu vyplnění od do a dalších polí v editaci dat jsem dal příkaz Uložit celý svazek a vygenerovala se hláška, vlastník je povinný, ačkoliv pole vlastní bylo vyplněno!! - viz printscreen 
![Snímek obrazovky 2022-09-25 v 11 34 54](https://user-images.githubusercontent.com/7532753/192138079-77698f71-8cf8-4b60-a383-8837b561761d.png)

Poté jsem tedy zkusil, zda pomůže funkce smazat celý svazek, abych mohl konečně uložit celý svazek, a vygenerovala se ta zmíněná chybová hláška.

**Comment by Kretiss** [comment]
@BrozekAles Opraveno na testu, byla chyba na backendu při kontrole obsahu exemplářů a id svazku. Chyba s vlastníkem by měla být také opravena.

**Comment by zabak** [comment]
@kretiss na produkci je stejná chyba jakou hlásil @BrozekAles při testování na testu zde: https://github.com/NLCR/evidence.periodik/issues/149#issuecomment-1257160037. Postupoval jsem stejně jak to popisuje on - vytvořil jsem exemplář (v Mladé frontě - testovací data) od 1.6. do 30.6., vlastník MZK a pak jsem se ho pokusil smazat.

**Comment by Kretiss** [comment]
@zabak Prosím ještě jednou o test, nasadil jsem opravu

**Comment by zabak** [comment]
funguje

**Comment by annavandasova** [comment]
@korhon otestovat prosím
