### ISSUE TITLE
Označení nejasného mutačního vydání

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#150]
U některých výtisků není patrné označení mutačního vydání. Zpravidla kvůli poškození titulní stránky. V takových případech by nemělo být pole prázdné, protože to naznačuje, že jde o mutační vydání bez označení. Navrhuji zapisovat v takových případech "N" jako "neznámé"
![image](https://user-images.githubusercontent.com/33937374/93759886-58084c00-fc0b-11ea-8e32-c4d6220b7b8d.png)

**Comment by zabak** [comment]
Pokud jsme si dostatečně jisti, že neexistuje mutační vydání nějakých novin značené písmenem N, tak souhlasím.

**Comment by zabak** [comment]
Bude doplněna hodnota "nečitelné" do seznamu mutačních vydání.

**Comment by holecInqool** [comment]
Vstúpil som do prehľadu exemplárov metatitulu Mladá fronta (TESTOVACÍ DATA).   
Jeden zo zväzkov som sa rozhodol editovať, do atributu "Mutační vydání" som bol schopný pridať akúkoľvek hodnotu vrátane "N", ktorá má reprezentovať stav "nečitelné".   
  
Následne v prehľade exemplárov vidím zoznam všetkých mutačných vydaní, vrátane hodnoty "N", ktorú majú dva záznamy. 

![](https://user-images.githubusercontent.com/89134583/152526317-caee05b5-c154-44df-a021-c798016ae75e.png)

Je cieľom, aby v tomto menu bolo napísané "N-nečitelné" alebo len "nečitelné"?   
  
Prípadne ako a kde sa má prosím prejaviť to, že do seznamu mutačních vydání bude pridaná hodnota "nečitelné"?

**Comment by zabak** [comment]
@korhon jak to vidíš?

**Comment by korhon** [comment]
Cílem je předat uživateli informaci, že u tohoto výtisku nejsme schopní mutační vydání identifikovat, protože je to na titulní straně nečitelné nebo to chybí. Mně připadá lepší, kdyby tady bylo napsáno "nečitelné"

**Comment by Kretiss** [comment]
@zabak opraveno a nasazené na testovacím serveru

**Comment by zabak** [comment]
otestováno, funguje
