### ISSUE TITLE
Pojmenování tabulek

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#154]
Pro lepší orientaci v návodu ke stránce "Editace svazku" nám připadá vhodné pojmenovat jednotlivé části - sekce tabulky. Uvádět v návodu formulace typu "tabulka vlevo nahoře" není úplně praktické. Navrhujeme použít například:
Editace vstupních dat
Tabulka denních vydání
Detailní popis svazku
![tabulky permonik](https://user-images.githubusercontent.com/33937374/94008314-17dbd180-fda3-11ea-8968-75a606fd0075.png)

**Comment by Kretiss** [comment]
@zabak opraveno a nasazené na testovacím serveru

**Comment by zabak** [comment]
otestováno, funguje
