### ISSUE TITLE
Úprava zápisu poznámek

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#156]
Při popisu exempláře je u některých defektů možné zadat "Popis". Např. u chybějících stran:
![image](https://user-images.githubusercontent.com/33937374/95087962-a0069300-0722-11eb-9400-3ddcc576f358.png)
Tento popis je ovšem společný pro všechny defekty (sloupce). Nebylo by možné zachovat popis pro každý defekt zvlášť a potom je souhrnně vypsat při najetí na tlačítko poznámky? 
Pokud bych chtěl doplnit poznámku, pak by se mi otevřel řádek s textovým polem tak jako teď, ale pod ním by se vypsaly všechny zapsané "Popisy", vždy každý na nový řádek...

**Comment by zabak** [comment]
Umožnit delší text do jedné poznámky (resp. zvětšit textové pole poznámky ve formuláři - možnost psát více vět na více řáádků), nedělat samostatná pole pro jednotlivé poznámky.

**Comment by zabak** [comment]
Odstranit pole popis u "chybí strany" a "poškozené strany", nechat jen čísla stran. Textový komentář psát do poznámky - zvětšit formulár pro poznámku. Při najetí a zakliknutí zatržítka "chybí strany" a "poškozené strany" se rovnou zobrazí bublina s čísly stran.

**Comment by Kretiss** [comment]
@zabak Nasazeno na vašem testu

**Comment by Chlupova** [comment]
Uložení poznámky ne vždy proběhne u čísla u kterého jsme otevřeli
příklad
otevřená poznámka u č. 145 z 20.6.1966 uložila se do 28.6.1966 č. 151, ale všechny další pokusy o uložení byly v pořádku, u stejného čísla i u jiných.
