### ISSUE TITLE
vymazaná data

### ISSUE THREAD

**Issue by frrezek** [NLCR/evidence.periodik#157]
Po editaci a uložení svazku NKP:

![image](https://user-images.githubusercontent.com/40558340/95336934-8e072a80-08b1-11eb-9ed4-6433febae59a.png)

se předpokládám nevratně vymazala data u svazku VKOL, a to nejen u čísel, která jsem editoval u našeho svazku, ale zdánlivě náhodně i u dalších čísel:
![image](https://user-images.githubusercontent.com/40558340/95337622-52b92b80-08b2-11eb-956e-1f7f01f6999d.png)

![image](https://user-images.githubusercontent.com/40558340/95337685-66fd2880-08b2-11eb-9d6c-bb52f7e38e6b.png)

**Comment by albertoh** [comment]
Zkoumam data... 
Mam otazku: svazek s carovym kodem 2650552708 jaky ma rozsah? Je spravny 3.1.1966 - 30.6.1966?
Pro NKP: Je mozne, ze otevreli jste svazek pro carovy kod 2650552708, zmenili jste ten carovy kod, a ulozili vsechno?

**Comment by frrezek** [comment]
V tom svazku VKOL (2650552708) jsme určitě nic neměnili..

**Comment by holecInqool** [comment]
Vzhľadom na to že p. albertoh podľa gitu tento probém už adresoval, bolo by prosím možné z Vašej strany otestovať, či ku chybe ešte stále dochádza rovnako, ako bolo popísané p. frrezek dňa 7. októbra 2020?

**Comment by frrezek** [comment]
v posledních měsících při zadávání nových svazků jsem už na tenhle problém nenarazil, tak snad je to v pořádku..

**Comment by annavandasova** [comment]
uzavírám a případně znovu otevřeme
