### ISSUE TITLE
Oprávnění uživatele jen ke svazkům jednoho vlastníka

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#158]
Uživatel by měl mít oprávnění editovat jen svazky jednoho vlastníka. Toto oprávnění nastavuje administrátor.

**Comment by zabak** [comment]
Viz. dohoda u #145 - nový uživatel nebude mít přiřazeného vlastníka, přidělí administrátor ze seznamu vlastníků.

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu

**Comment by zabak** [comment]
funguje

**Comment by ludvicekj** [comment]
mě funguje správně, ale #212
