### ISSUE TITLE
Prolink od metatitulu na svazky

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#159]
V této chvíli není možnost se od metatitulu prokliknout na seznam svazků, přidat prolink.

**Comment by zabak** [comment]
Upřesnění: do správy metatitulu přidat checkbox "zobrazovat nepřihlášeným uživatelům"

**Comment by holecInqool** [comment]
Overím si, či rozumiem obom požiadavkom správne:   
  
1\. Keď si v záložke metatituly (napr. http://195.113.132.165:8080/permonik/titul) kliknem na metatitul "Mladá fronta (TESTOVACÍ DATA)", malo by tu byť tlačidlo, ktoré ma presunie na Přehled exemplářů (http://195.113.132.165:8080/permonik/result/1B569F5B32DD652280C63F6DB9C324D15E510C06), rovnako ako sa to deje keď v hlavnom menu pod metatitulom "Mladá fronta (TESTOVACÍ DATA)" kliknem na ružové tlačidlo "1530 záznamů"?   
  
2\. V správe metatitulu (viď. screenshot) by malo pribudnúť tlačidlo "zobrazovat nepřihlášeným uživatelům", podľa ktorého sa titul skryje/zobrazí neprihláseným užívateľom. 

![](https://user-images.githubusercontent.com/89134583/152528805-3bde3ce5-d14a-4ea1-b0ea-a2c62f2b74bc.png)

Je to tak?

**Comment by zabak** [comment]
Ad 1 ano - ta stránka je sice hlavně konfigurační, ale má smysl, aby tam bylo obdobné tlačítko tomu růžovému - klidně i s tím počtem záznamů.
Ad 2 nikoli tlačidlo, ale zatržítko typu Ano/ne. Ve #169 chceme odstranit položku Metatituly z menu pro nepřihlášené uživatele, takže to zatržítko se bude vztahovat jen na zobrazení metatitulu na kartách na hlavní stránce.

**Comment by Kretiss** [comment]
@zabak Ad 1 je na testu, Ad 2 bude složitější, v appce moc nefunguje nějaké obnovování dát a ošetřování dat na základě změny přihlášení..

**Comment by zabak** [comment]
Ad 1 otestováno, v pořádku. Zbývá tedy ad 2. Dávám label opravit, kvůli té dvojce.

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu, prosím o vyzkoušení. Momentálně jsou všechny metatituly skryty pro nepřihlášené uživatele.

**Comment by Kretiss** [comment]
@zabak Poprosím o kontrolu **ad 2**, nasazeno na testu.

**Comment by zabak** [comment]
Ano, funguje
