### ISSUE TITLE
Označení mutačního vydání

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#160]
Po jednání minulý týden, kde jsme se zabývali zápisem mutačního vydání, jsme tento týden prošli všechny metatituly uvažované pro PerMonika. Ve skladu jsme ověřovali, jakými způsoby jsou označena mutační vydání a došli jsme k tomu, že skupina značek je ustálená. Opakují se tyto symboly:
tečka
čtvereček
hvězdička
nic

Proto se nám jeví jako optimální vybírat znak z přednastavené nabídky. 
U Lidové demokracie jsme narazili na zcela jiný způsob zápisu - "I. vydání" a "VI. vydání". Ale protože do pole jde zapisovat, nevidíme to jako problém.

**Comment by zabak** [comment]
Bude existovat seznam povolených názvů mutačních vydání pro daný metatitul, ten může upravovat každý uživatel v administraci, z něj se vybírá.

**Comment by Kretiss** [comment]
@zabak  Můžu poprosit o seznam povolených znaků k metatitulům? Zároveň bych se chtěl zeptat, jestli se jedná o pole viz obrázek. Děkuji

<img width="478" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/181766724-d8a27de3-330b-4925-9af4-de716c2a1bac.png">

**Comment by zabak** [comment]
Ano, jedná se o pole označené na obrázku.

**Comment by zabak** [comment]
@korhon prosím dodat seznam povolených znaků

**Comment by korhon** [comment]
Seznam probereme na nejbližší schůzce.
◼◼◼◼
◻◻◻◻
●●●●
⭘⭘⭘⭘
✱✱✱✱

**Comment by Kretiss** [comment]
@zabak Při nasazování na test jsem toto issue nakousl, momentálně je tam forma inputu s autocomplete, který ukazuje různé kombinace. Pokud se dá dohromady finální seznam znaků, bude tam přímo select.

**Comment by ludvicekj** [comment]
možné znaky v unicode: 
https://unicode-table.com/en/25CF/ 
https://unicode-table.com/en/25CB/ 
https://unicode-table.com/en/2B58/ 
https://unicode-table.com/en/25A0/ 
https://unicode-table.com/en/25A1/ 
https://unicode-table.com/en/002A/ 
https://unicode-table.com/en/2731/ 
https://unicode-table.com/en/066D/

**Comment by zabak** [comment]
●●○○■■□□**✱✱
ten poslední je divný, tomu bych se vyhnul ٭٭

**Comment by ludvicekj** [comment]
★★★★★ 
https://unicode-table.com/en/2605/

**Comment by ludvicekj** [comment]
jako tabulku znaků pro vložení v poli Mutační vydání v Editaci svazku
![image](https://user-images.githubusercontent.com/40558551/201081362-56060431-d04a-4f48-8391-770b7af5464e.png)

**Comment by Kretiss** [comment]
@korhon @zabak @ludvicekj Nasazeno na testu, možnost **bez označení** jsem vynechal, protože ta znamená prázdné pole (výchozí hodnota)

**Comment by zabak** [comment]
@Kretiss funguje, ale ta tabulka se neobjeví pokud chci editovat údaj u jednotlivého vydání.
<img width="146" alt="image" src="https://user-images.githubusercontent.com/811537/211021680-4a9c1129-47fd-497b-b56a-5476785985a0.png">

Zároveň jsem si všiml, že vložení funguje jen pokud je pole prázdné - není možné do něj napsat jiný znak a pak chtít vložit třeba hvězdičku. To je podle ě správné chování protože se mutační vydání vždy označuje výhradně jedním nebo několika shodnými znaky. Je to tak? @korhon @ludvicekj

**Comment by zabak** [comment]
funguje

**Comment by ludvicekj** [comment]
na produkci funguje
