### ISSUE TITLE
Chybí číslo

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#161]
Kde vznikl sloupec "Chybí číslo" v editaci svazku? Vůbec si nevybavuju jeho funkci a nechápu ho. To že číslo existuje se zadává na začátku řádku... Pokud chybí, tak se to zapíše tam.

**Comment by albertoh** [comment]
Ja to chapu tak, ze chybi cislo v tom svazku (nemame ho), ale mel by existovat. 
Tenhle stav uz davno existoval v seznamu stavu... Pridal jsem ho tam, aby se jednoduse dalo odznacit. 
To ma navaznost na opravu #111, kde se ted vypisujou cisla tak odznacene

**Comment by korhon** [comment]
To mi připadá trochu nadbytečné. To že číslo chybí, přestože existuje, naznačuje mezera v kompletní řadě číslování. Měl jsem za to, že je to úplně dostačující i k řešení té #111  Díra v řadě znamená že číslo chybí. To nestačí?

**Comment by zabak** [comment]
Sloupec "chybí číslo" odstranit včetně dat.

**Comment by zabak** [comment]
Zároveň přejmenovat "číslo existuje" na "je ve svazku"

**Comment by Kretiss** [comment]
@zabak Nasazené na testu, prosím o kontrolu

**Comment by zabak** [comment]
Po odstranění sloupce chybí číslo zůstala po něm ve formuláři asi díra - sloupec mutační vydání je najednou dvojnásobně široký
<img width="189" alt="image" src="https://user-images.githubusercontent.com/811537/183420198-12aa5d80-757f-45a4-9654-fbeb5eec3f5e.png">

**Comment by Kretiss** [comment]
@zabak Opraveno na testu

**Comment by zabak** [comment]
ověřeno, funguje

**Comment by annavandasova** [comment]
data zůstala, viz fasety, prosíme odstranit

**Comment by annavandasova** [comment]
@Kretiss

**Comment by Kretiss** [comment]
@zabak Upravil jsem data na produkci
