### ISSUE TITLE
Vertikální odsazení víceřádkových faset

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#165]
Je potřeba zmenšit řádkování v rámci fasety a zachovat stejné svislé odstupy mezi jednotlivými fasetami. 

![image](https://user-images.githubusercontent.com/811537/126082721-a3d0e14e-fd2d-448e-bebf-ea833c4cbd56.png)

**Comment by zabak** [comment]
Nevidím změnu

**Comment by mysliktomas** [comment]
@zabak Nedaří se mi problém s překrytím řádků nasimulovat, mohu poprosit o retest, zda to stále trvá a případně detailnější info za jakých okolností tento problém nastává. Děkuji

**Comment by zabak** [comment]
@mysliktomas testoval jsem v Chrome, Firefoxu a Safari na Macu a v Chrome na Androidu, všude se to takto chová. https://permonik.inqool.cz/permonik/result/1B569F5B32DD652280C63F6DB9C324D15E510C06

**Comment by annavandasova** [comment]
za mě ok, co @zabak ?

**Comment by zabak** [comment]
za mě je to pořád nevyřešený problém

**Comment by annavandasova** [comment]
mně  se to v chromu ukazuje dobře, kde je u tebe problém?

**Comment by annavandasova** [comment]
tak beru zpět, u MF (testovací) to je pořád jako na obrázku. U Čsl. sportu je to v pořádku.

**Comment by Kretiss** [comment]
@zabak opraveno a nasazené na testovacím serveru

**Comment by zabak** [comment]
Díky, funguje.
