### ISSUE TITLE
menu pro zadání data

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#166]
Pokud zadávám datum přes vybírací tabulku, tak mi nabízí roky z budoucnosti:

![image](https://user-images.githubusercontent.com/811537/126082981-584fbc12-57dc-49aa-b638-c62c5a96fb20.png)

Logické by bylo zobrazit roky nejvýše po současný rok. Zároveň bych limitoval počátek. @Foltom @AnnaCajthamlova  prosím řekněte spodní hranici: 1600, 1700, 1800, 1848, 1900 nebo 1918?

Roky by se nemělo listovat po 24 ale po 20 nebo 25. Ideálně tabulka 5x5 roků.

Roky mimo uvedené hranice by nemělo být možné ani zadat.

**Comment by zabak** [comment]
Pokud zadám v editaci vstupních dat "datum od", mělo by se automaticky do "datum do" doplnit datum posledního dne měsíce zadaného v "datum od" aby se nemusel hledat znovu rok.

**Comment by zabak** [comment]
A ještě jedna věc: pokud zadávám datum ručně, nemělo by být možné zadat nesmyslné datum typu 32.14.1976. A mělo by se hlídat, že datum od je menší než datum do.

**Comment by zabak** [comment]
V současnosti pokud zadám datum jako text (i správné) tak to vyhodí při pokusu o uložení hlášku snackbar.datum_do is required. Což ale pak nedává smysl, proč je možné datum vepsat i ručně?

**Comment by mysliktomas** [comment]
Jaká je tedy prosím spodní a horní hranice nabízených datumů?
Je žádoucí umožnit zapsat datum ručně či umožnit pouze výběr z kalendáře?
K tomu je tedy potřeba následující:
- listovat roky po 25 v tabulce 5x5
- omezit zadání datumu mimo uvedené hranice
- automatické doplnění pole "datum do" - poslední den měsíce vybraného v poli "datum od"
- kontrolovat správnost zadaného data
- kontrolovat zda je "datum od" menší než "datum do"

**Comment by AnnaCajthamlova** [comment]
@zabak okomentuješ prosím?

**Comment by Kretiss** [comment]
@zabak opraveno a nasazené na testovacím serveru s tím, že listování let upravit nepůjde kvůli vazbě na knihovnu přes kterou je aplikace vytvořená. Neumožňuje takové hluboké úpravy vzhledu.

**Comment by zabak** [comment]
Po editaci data zůstane řádek černý
<img width="488" alt="image" src="https://user-images.githubusercontent.com/811537/182544857-d12d649f-558d-4cde-8861-3c42d7644d33.png">

Vkládat datum je možné jen z kalendáře, ale to by myslím nemuselo vadit. Takže za mě zůstává jen ten černý řádek po zadání údaje.

**Comment by Kretiss** [comment]
@zabak Mělo by být opraveno, prosím o test

**Comment by zabak** [comment]
funguje
