### ISSUE TITLE
editace vstupních dat - zapamatovat si naposledy vložené hodnoty

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#167]
Cílem je ušetřit lidem práci, protože zadávají pořád to samé dokola. Když systém zatuhne, taky se hodí nemuset vše vyplňovat znova.

**Comment by zabak** [comment]
Myšleno u formuláře "Editace vstupních dat" a "Tabulka denních vydání"

**Comment by AnnaCajthamlova** [comment]
Zapamatovat si hodnoty ještě před uložením

**Comment by Kretiss** [comment]
@zabak Tady je myšleno zapamatovat si posledně vyplněné, ale neuložené údaje lokálně v rámci jednoho počítače/mobilu? Nebo globálně v rámci uživatelského účtu? Po návratu na svazek by vyskočilo okno s možností načtení uložených dat, které by se patřičně zvýraznily. Taky bych tam dal možnost uložená data zapomenout/automaticky zapomenout po prvním nevyužití.

**Comment by zabak** [comment]
Stačí lokálně v rámci jednoho browseru.  A mohlo by to být tak, že to nabídne použití posledně zadaných hodnot, ať už byly uložené nebo ne. Prostě to co v tom formuláři bylo naposledy by bylo možné do něj znovu předvyplnit.

**Comment by zabak** [comment]
Udělat to co je jednodušší, buď toto nebo #174

**Comment by annavandasova** [comment]
až v nové aplikaci

**Comment by Kretiss** [comment]
Nebude realizováno
