### ISSUE TITLE
Psaní poznámek

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#168]
Po uložení Poznámky se někdy Poznámka přemístí k jinému výtisku. Jsou také problémy s úplným smazáním poznámky (nikoliv s úpravou textu poznámky)

**Comment by BrozekAles** [comment]
Možná ten problém vzniká poté, co se vloží další vydání...

**Comment by Kretiss** [comment]
@BrozekAles Nasazeno na našem testu, prosím o kontrolu.

**Comment by BrozekAles** [comment]
Problém přetrvává viz printscreen (psal jsem poznámku k výtisku ze 4.1., poznámka se dostala do 5.1. 
![Snímek obrazovky 2022-09-25 v 11 43 21](https://user-images.githubusercontent.com/7532753/192137524-274b2f2a-bad0-40f1-88b7-01bfbc345502.png)

**Comment by zabak** [comment]
@BrozekAles prosím o otestování na produkci

**Comment by BrozekAles** [comment]
Problémy s psaním poznámek jsem měl opět i na produkci, ale nedá se usoudit, kdy k tomu dochází. Prosím někoho z Inqool na domluvení termínu, kdy bych se přihlásil přes Zoom a nasdílel svou obrazovku, aby se dalo sledovat, kdy se přemístí poznámka k jinému výtisku

**Comment by Kretiss** [comment]
@BrozekAles @zabak Zkoušel jsem to teď znova ty poznámky a zase se mi nepodařilo to nasimulovat, ikdyž se mi to na schůzce projevilo. Posunul jsem tedy text poznámky co se ukaze při najetí doleva, uvidíme, jestli to něco změní nebo ne...

**Comment by zabak** [comment]
Považuji za vyřešené. Pokud se problém znovu objeví, založíme nové issue.
