### ISSUE TITLE
Úprava hlavního menu 

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#169]
Pro nepřihlášené bude viditelná v menu jen změna jazyků, přihlášení a home.

Pro přihlášené bude položka metatituly viditelná jen pro toho kdo k ní má práva, totéž pro správu uživatelů.

"vložit záznam" bude odstraněno **včetně funkcionality**

**Comment by mysliktomas** [comment]
Mohu poprosit o upřesnění, které oprávnění umožní uživateli vidět položky "metatituly" a "správa uživatelů"?
Akce "vložit záznam" chápu správně, že má být odstraněn jako celek, tj. nebude např. omezený oprávněními?

**Comment by AnnaCajthamlova** [comment]
@zabak

**Comment by zabak** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/811537/172408835-b153e0a1-613c-4bf8-ba1f-99a5950c346f.png">
Číslu u "Exemplářů" je ptřeba nechat víc prostoru na úkor obou ostatních. Není problém mít desítky nebo i stovky tisíc vydání, ale mutací a vlastníků bude hodně

**Comment by zabak** [comment]
@mysliktomas Správu uživatelů i metatituly by měli vidět jen admini, protože přehled metatitulů je už na home obrazovce.

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu, prosím o kontrolu. Záložky _metatituly_ a _správa_ se skrývají pro nepřihlášené/ovyčejné uživatele. Text v kartách na home pagi upraven. Pole _vložit záznam_ je odstraněno jak má být? Nemůžu to podle názvu moc najít, ale vypadá to, že je to pryč, prosím o zpětnou vazbu.

**Comment by zabak** [comment]
zdá se mi, že je vše v pořádku.
