### ISSUE TITLE
Editace svazku

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#171]
I bez přihlášení lze otevřít svazek a zdánlivě jej editovat. Funkce "Uložit celý svazek" je sice vypnuta, ale je na levé straně, takže se při editování svazku  může stát, že si ukládající všimne vypnuté funkce "Uložit celý svazek" poté, co editoval řadu čísel. Je tedy třeba udělat takovou úpravu, aby bez přihlášení nemohl ukládající ani zdánlivě svazek editovat.

**Comment by zabak** [comment]
Znemožnit přístup do editace pro nepřihlášeného uživatele.

**Comment by Kretiss** [comment]
@zabak Nasazeno na inqool testovacím serveru

**Comment by BrozekAles** [comment]
No mně se teď podařilo smazat dva exempláře (ověřoval jsem funkčnost ikony smazat exemplář) u 314800329591 (rok 1953, č, 2 a 3), a to jsem dokonce nebyl přihlášen!

**Comment by zabak** [comment]
@BrozekAles Zakládám issue #195 s tímto problémem - jedná se o jinou stránku.
