### ISSUE TITLE
Neexistující čísla

### ISSUE THREAD

**Issue by korhon** [NLCR/evidence.periodik#172]
V hlavní přehledové tabulce se zobrazují čísla, která ve svazku nejsou, v editaci svazku je u nich vynechaný řádek, přesto se promítnou do tabulky a navíc se stavem "Nekontrolováno". 
Příklad Čs. sport 5.9.1976 je neděle, nevyšla, nebyla vygenerována, přesto je v tabulce
VKOL ČK 265A004984

**Comment by MartinOsif** [comment]
![5  9  1976](https://user-images.githubusercontent.com/95423008/144431291-6f6f787e-e9d6-413b-94ab-e9735a7fb95d.PNG)

**Comment by BrozekAles** [comment]
Navíc je možnost se dostat k těm "číslům" přes editovat záznam. Např. u svazku 314800329639 z 1. kv. 1977 u 1. ledna, kdy žádné číslo kvůli svátku nevyšlo, bylo u tohoto neexistujícího výtisku uvedeno číslo 0 a nekontrolováno. Když jsem se na to podíval přes editovat záznam, tak se automaticky u tohoto výtisku vytvořilo číslo 1, to se nedalo odstranit, i když jsem napsal znovu nula, a dostalo se to do přehledové tabulky :-(  Navíc se takové blbosti dostávají i do statistik (faset)

**Comment by Kretiss** [comment]
@korhon @BrozekAles Momentálně to funguje tak, že pokud se vytvoří nový metatitul a v něm svazek s počtem exemplářu třeba 31 a dá se vygenerovat, tak se vygeneruje 31 exemplářů, kterým ale chybí ty údaje co se zaklikávají potom dál v tabulce. Problém vidím v tom, že ten exemplář existuje, ikdyž by vlastně neměl, viz přiložené obrázky. Generoval jsem pondělí, úterý, čtvrtek, první číslo je 0, poslední číslo je 31. Vygenerovalo to všechn 31 exemplářů, ikdyž to vůbec není potřeba, viz druhý screen a pole **"numFound":31**. 

<img width="1433" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/189304392-f6665b29-eb1f-42d5-972b-de202a9d8bad.png">
<img width="573" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/189304497-74b00426-a63f-4a11-8b3c-d540d486ec9d.png">

**Comment by Kretiss** [comment]
@korhon @BrozekAles Nasazeno na našem testu. Generování dat, které jsem komentoval předtím musí zůstat tak jak je. Filtruje se to ale na úrovni databáze na základě **numExists**, takže se zbytečné exempláře nepřenáší.

**Comment by zabak** [comment]
@korhon prosím o otestování

**Comment by zabak** [comment]
@korhon prosím o otestování na produkci

**Comment by zabak** [comment]
@korhon připomínám
