### ISSUE TITLE
Přejmenovat tlačítko "Znovu našíst celý svazek" na "Zrušit změny"

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#173]
![image](https://user-images.githubusercontent.com/811537/142006232-3e9f8a18-defa-475b-8528-13f2f3243afd.png)

**Comment by zabak** [comment]
nelze otestovat, protože daná stránka se nenačte

**Comment by BrozekAles** [comment]
mám stejný problém, přihlásím se sice na https://permonik.inqool.cz/ svým heslem a mohu, zdá se, dělat stejné dotazy (filtrování dotazu), ale protože není v nabídce "Svazek", nemohu otestovat
