### ISSUE TITLE
Detailní popis svazku: Upozornění na předčasné odejití ze stránky

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#174]
Při vyplňování levé části tabulky v Editaci svazku:

Pokud nevyplním údaje aspoň o jednom výtisku do detailního popisu svazku a kliknu na Home, už pravou část tabulky (Editace vstupních dat a Tabulka denních vydání) nenajdu a musím znovu editovat vstupní data svazku. Neobjeví se totiž ta ikonka vedle údaje o čárovém kódu pro editaci svazku. 

Bylo by dobré se při odchodu z této stránky zeptat uživatele jestli si je jistý, že chce stránku opustit.

**Comment by Kretiss** [comment]
@zabak nasazeno na testu

**Comment by zabak** [comment]
funguje

**Comment by annavandasova** [comment]
funguje
