### ISSUE TITLE
Nelze editovat svazek

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#175]
U některých svazků, které byly ukládány do PerMonik v SVKUL, nelze provést dodatečnou editaci svazku, tedy po kliknutí na ikonu  vedle čárového kódu (např. 314800329591) se neukáže detailní popis svazku, resp. se ukáže, ale nejsou v něm vyplněné údaje.     Zatímco u jiných svazků (např. 314800329635) se detailní popis svazku ukáže.

**Comment by mysliktomas** [comment]
Ano poprosím vás o kompletní seznam, předem děkuji.

**Comment by BrozekAles** [comment]
Dobře, zde je úplný seznam svazků, kde byl vlastníkem svkul. Nelze editovat svazky s těmito čárovými kódy (v závorce je údaj “od-do” z editace vstup. dat):  314800329591 (svazek pro celý rok 1953, ale v editaci svazku pro “od do” uveden jen prosinec 1953), 314800329594 (prosinec 1955), 314800329595 (prosinec 1956), 314800329596 (prosinec 1957), 314800329597 (prosinec 1958), 314800329598 (září-pros. 1959), 314800329599 (červenec-pros. 1960), 314800329601 (listopad-pros. 1961), 314800329602 (březen-červen 1962), 314800331278 (duben-červen 1965), 314800331279 (říjen-prosinec 1965), 314800329605 (květen-červen 1966), 314800329604 (říjen-prosinec 1966), 314800329607 (květen-červen 1967), 314800329606 (říjen-prosinec 1967), 3148003331280 (květen-červen 1968), 3148003331281 (prosinec 1968), 314800329636 (červen 1976), 314800329637 (září 1976)

**Comment by Kretiss** [comment]
@zabak Mělo by být opraveno, poprosím o test

**Comment by holecInqool** [comment]
Pred malou chvíľou bolo nasadené na DEV prostredie (https://permonik.inqool.cz/permonik). 

Pozitívna zmena je viditeľná pre svazky špecifikované p. @BrozekAles - zatiaľ čo svazky nejde editovať (nezobrazí dáta) na produkčnom prostredí (http://195.113.132.165:8080/permonik), na DEV prostredí editovať idú (zobrazí dáta).

**Comment by BrozekAles** [comment]
Ano, je to pozitivní změna, v DEV prostředí to funguje, doufejme, že to bude fungovat i v produkčním prostředí, až se tam nasadí opravená verze PerMonik

**Comment by BrozekAles** [comment]
znovu otvírám issue, protože nelze editovat začátek roku 1954, čár. kód 314800329592
Navíc u dat od 2.2.1954 se dostal u editace vstupních dat do pole čár. kód text znění "Prohozené strany 3 a 4 ve vazbě" (text z pole poznámka u detailního popisu svazku)
Bylo by dobré upravit tak, aby do pole čk se mohly vkládat jen numerické znaky

**Comment by Kretiss** [comment]
@BrozekAles Poprosím zkusit tlačítko **vygenerovat / vygenerovat znovu** a následně **uložit svazek**. Z nějakého důvodu se v rozsahu svazku nenacházely žádné uložené exempláře. Je možné, že to vzniklo díky předešlým chybám, momentálně nedokážu přesně říct proč.

**Comment by BrozekAles** [comment]
tlačítko vygenerovat / vygenerovat znovu a následně uložit svazek jsem nyní u 1. pololetí 1954 čár. kód 314800329592 použil  v prostředí Inqool a dostal se tak k možnosti editovat svazek. Opravil jsem v editaci vstupních dat datum od 1.1. do 29.6. (bylo tam od 2.2. do 27.2.) a uložil celý svazek. Nyní nemohu editovat v tomto svazku čísla od března do konce června!

**Comment by Kretiss** [comment]
@BrozekAles Zkusil jste obnovit stránku svazku? Po uložení se nezobrazí nový rozsah exemplářů, po opětovném načtení se zobrazí vše správně a vše mi jde normálně ukládat a editovat. Prosím znovu o test nebo konkrétnější popsání problému.

**Comment by BrozekAles** [comment]
Myslíte "načíst tuto stránku znovu" (tedy obecný refresh stránky)? To  
je snad totéž, jako když po ukládání z PerMonika odejdu a znovu se  
přihlásím. A zkoušet to mám v produkčním prostředí nebo zatím jen v  
testovacím?



  - Ing. Aleš Brožek m: + 420 731 578 269
  e: ***@***.*** Severočeská vědecká knihovna v Ústí nad Labem
  The North Bohemian Research Library in Ústí nad Labem

  Winstona Churchilla 3
  400 02 Ústí nad Labem
  Czech Republic


----------------původní zpráva-----------------
Od: "Tomáš Kretek" ***@***.*** ]
Komu: "NLCR/evidence.periodik" ***@***.*** ]
Kopie: BrozekAles ***@***.*** ], Mention ***@***.*** ]
Datum: Thu, 18 Aug 2022 14:22:48 +0200
----------------------------------------------------------

**Comment by Kretiss** [comment]
@BrozekAles Ano myslím obecný refresh stránky nebo jak jste psal, odejít z permoniku a znovu se přihlásit. Jednoduše řečeno, nějak se na tu danou stránku dostat "znovu". S tímhle postupem to nefungovalo?

**Comment by BrozekAles** [comment]
Ano, refresh nepomůže. Po dnešní online poradě jsem v produkčním prostředí u 1. pololetí 1954 čár. kód 314800329592 znovu editoval svazek, opravil jsem v editaci vstupních dat datum od 1.1. do 30.6. (bylo tam od 2.2. do 27.2.) a uložil celý svazek. Nyní nemohu editovat v tomto svazku čísla od března do konce června, resp. data za toto období zmizela.






 Opravil jsem i  pole čár. kód text znění "Prohozené strany 3 a 4 ve vazbě" na správný čár. kód 314800329592, v detailním popisu svazku nyní chybí data za období 2.2. až 27.2., bude je nutné znovu vložit. 
![Snímek obrazovky 2022-08-25 v 12 40 26](https://user-images.githubusercontent.com/7532753/186644718-f8275379-874a-4120-8a68-51c3119dfdf0.png)

**Comment by BrozekAles** [comment]
![Snímek obrazovky 2022-08-25 v 12 42 18](https://user-images.githubusercontent.com/7532753/186645238-15c2736a-6fde-40a3-9ddf-6ce595ebd18e.png)
![Snímek obrazovky 2022-08-25 v 12 40 50](https://user-images.githubusercontent.com/7532753/186645371-efe460c1-8f2f-4460-9950-49fdc495fdb6.png)
