### ISSUE TITLE
Nezobrazují se všechny uložené exempláře

### ISSUE THREAD

**Issue by MartinOsif** [NLCR/evidence.periodik#176]
Permoník zobrazuje max. 5000 exemplářů. Při 
ukládání už jsem to číslo překročil, ale nedokážu se na 
exempláře podívat, jestli jsou vůbec uložené. Mohl by správce 
dát větší limit? Případně aby konečné číslo 
korespondovalo s počtem záznamů?
![Snímek obrazovky 2022-01-18 120628](https://user-images.githubusercontent.com/95423008/149941250-0122295f-ab85-407a-af6f-e1b23922159f.png)

**Comment by BrozekAles** [comment]
Na další exempláře se lze podívat, že se v datumu od do změní interval na kratší období než na současné období 1953 - 1989, ale větší limit podporuji, stejně jako zvětšit nabídku "Items per page" na 300, aby se rychleji kontrolovaly jednotlivé roky

**Comment by Kretiss** [comment]
@BrozekAles Upravil jsem maximální počet exemplářů na 20 000. To by mělo na chvíli vystačit. Počet exeplářů na stránku je nyní 25, 50, 500, 1000. Prosím o kontrolu na testu.

Do budoucna by tohle chtělo pohlídat a vymyslet rozumněji. Pro představu, při načítání asi 9500 exemplářů z databáze se přenese najednou 14.5MB dat, což není zrovna málo, nehledě na to, že nevím, jaké výkonostní kapacity má server.

**Comment by zabak** [comment]
funguje
