### ISSUE TITLE
Filtr "nekontrolováno"

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#177]
Mám pocit, že nelze vyfiltrovat výtisky, které nebyly kontrolovány v daném svazku. Aspoň ve fasetě Stav nevidím žádný takový údaj a přitom některé výtisky ve  svazku s čár. kódem 2650516426 nejsou kontrolované...

**Comment by Kretiss** [comment]
@BrozekAles Prosím o kontrolu, nasazeno na testu. Ve výpisu filtrů se ovšem zobrazuje místo množství nekontrolovaných výtisků otazník. Snad to nevadí, je to takhle řešení díky stavbě kódu. Účel to ale plní.

**Comment by BrozekAles** [comment]
Ty otazníky by nevadily, spíše mne překvapuje, že stále to píše Nalezeno záznamů 5499, i když jsem požadoval jen ty, kde je vlastník svkul, a jak ukazuje printscreen, ukáže to i nekontrolované v MZK a VKOL
![Snímek obrazovky 2022-08-25 v 16 46 10](https://user-images.githubusercontent.com/7532753/186697176-90232e55-f9ed-4c8b-8921-8748067c60bb.png)

**Comment by Kretiss** [comment]
@BrozekAles opraveno na testu.

**Comment by zabak** [comment]
@BrozekAles prosím o kontrolu

**Comment by BrozekAles** [comment]
Kontroluji problém na svazku s čár. kódem 314800329591. Podle fasety "Stav" a "chybí číslo" chybí 4 čísla (8, 50, 61, 103) a dle fasety "nekontrolováno" 1 číslo (26), ale domnívám se, že by mělo být "nekontrolováno" 5 čísel (8, 26, 50, 61, 103). A záhadou pro mne je fakt, že se nevygenerovaly údaje o číslech 41, 42 a 43

**Comment by Kretiss** [comment]
@BrozekAles U těch čísel 41, 42, 43 chybí zakliknuté "je ve svazku", proto tam nejsou. Taky tam ty čísla nikde nevidím, ale to musel někdo špatně zakliknout nebo se to někdy předtím blbě uložilo, když nefungovalo správné načítání toho přehledu. Stav chybí číslo má z databáze zmizet, to musím teprve smazat, řešilo se to v jiném issue. Zkuste to kdyžtak znovu, ale dle mého ty filtry fungují.

**Comment by ludvicekj** [comment]
myslím, že při správném vyplnění v Editaci svazku, ukazuje filtr "Nekontrolováno" správně..

**Comment by BrozekAles** [comment]
zdá se, že v produkčním prostředí filtr "nekontrolováno" funguje správně
