### ISSUE TITLE
Nelze dodatečně dopsat ke svazku vlastníka

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#180]
Když se při editaci nového svazku zapomene v editaci vstupních dat vyplnit pole vlastník, není možné si otevřít editaci vstupních dat přes ikonu editovat svazek vedle čárového kódu (v pravé polovině displeje) a dopsat vlastníka. Nutno provést znovu editaci nového svazku. To ale způsobí, že se v tabulce detailní popis svazku každé číslo periodika objeví 2x a duplicitní číslo se musí  "mazat" odškrtnutím políčka "číslo existuje"

**Comment by BrozekAles** [comment]
Hm, odmazávání duplicitních čísel není snadné, protože se nepozná, ke kterému číslu se přiřadil údaj o vlastníkovi a ke kterému číslu se nepřiřadil údaj o vlastníkovi, protože se nevyplnil. Mohla by se udělat úprava editace vstupních dat tak, že pokud není vyplněn čárový kód a vlastník, nelze "uložit celý svazek"?

**Comment by BrozekAles** [comment]
A ještě bych doporučoval, aby proběhl úkon "uložit celý svazek" až poté, co systém zkontroluje, nejen zda je vyplněn údaj o vlastníkovi, ale i čárový kód, a zda čárový kód obsahuje jen numerické znaky (aby se do pole čárový kód nemohl dostat text z pole poznámka, jako tomu bylo v případě svazku svkul z 1. pololetí 1954. Díky.

**Comment by Kretiss** [comment]
@BrozekAles Prosím o kontrolu, nasazeno na testu (doplněna funkce kontroly čárového kódu jako čísla).

**Comment by BrozekAles** [comment]
Ano, funguje to, nepustí mne to, když nevyplním údaj o vlastníkovi. Také nemohu napsat čárový kód jako alfanumerický, pouze jako numerický (ještě by bylo dobré, aby se ostatní vyjádřili, zda jejich čárový kód je vždy tvořen 12 číslicemi (našel jsem teď u svkul napsaný čárový kód třináctimístný, což vzniklo upsáním :-(   A ostatní by se mohli vyjádřit, zda by bylo dobré, kdyby při vytváření nového svazku zároveň systém kontroloval, zda nebyl ten čárový kód použit už jindy. A ani netuším, zda lze v Permoniku vyhledávat podle čárového kódu, když budu potřebovat něco opravit. Zdá se mi, že se dá vyhledávat jen podle roku, přitom v rámci jednoho roku může být více svazků a potřebuji rychle najít jen ten určitý svazek

**Comment by zabak** [comment]
@BrozekAles standardní délka čárového kódu je 10 znaků, pokud má svkul 12 znaků tak to je samo o sobě nestandardní. Viz. https://www.techlib.cz/cs/2920-carove-kody-pro-ceske-knihovny

**Comment by zabak** [comment]
považuji za hotové, pokud bude problém se zápisem čárových kódů, vytvoří se nové issue

**Comment by BrozekAles** [comment]
v produkčním prostředí v pořádku - musím napsat vlastníka, jinak mne to nepustí

**Comment by zabak** [comment]
@Kretiss prosím ještě o ostranění všech 9 záznamů bez vlastníka na produkci z metatitulu Mladá fronta - testovací data

**Comment by Kretiss** [comment]
@zabak Smazáno na produkci

**Comment by zabak** [comment]
díky, zavírám
