### ISSUE TITLE
Opravit alt text 

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#182]
<img width="140" alt="image" src="https://user-images.githubusercontent.com/811537/173112615-0b57a405-929d-4c02-9fdb-4ad98030c654.png">
Duplicate exemplář -> Duplicitní exemplář

**Comment by Kretiss** [comment]
@zabak Prosím o kontrolu, nasazeno na testu.

**Comment by zabak** [comment]
zkontrolováno, prosím o nasazení

**Comment by Kretiss** [comment]
@zabak nasadíme kdyžtak s ostatníma změnama co teď proběhly

**Comment by korhon** [comment]
Tam asi mělo být spíš duplikovat než duplicitní, ale mělo by to přijít pryč úplně. Viz #186

**Comment by zabak** [comment]
@Kretiss tak to nasaďte ať to má nějakou koncovku.

**Comment by Kretiss** [comment]
@zabak Pokud to nasadím, nasadím to i se změnami, co čekají na test

**Comment by zabak** [comment]
@Kretiss tak jsem to myslel.
