### ISSUE TITLE
Přečíslovat dolů - UX

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#183]
Jak bylo diskutováno ve #140, funkce "přečíslovat dolů" funguje, ale je udělená neohrabaně. Přečíslovává se okamžitě když uživatel klikne na šipku.  To že akce proběhla se ale nijak neprojeví, než tím, že se čísla změní. To je nebezpečné proto, že když se uživatel uklikne na už zpracovaném svazku, tak se mu zničí všechny úpravy které předtím už udělal. Bylo by dobré aby se před uděláním akce zobrazil dialog typu "bude přečíslováno xx čísel, chcete to udělat?" a po přečíslování zahlásit něco jako "bylo přečísováno xx číslel (od x po y).

Otevírám k prodiskutování

**Comment by annavandasova** [comment]
jednoznačně souhlasím

**Comment by BrozekAles** [comment]
Taky souhlasím, ale zdá se mi přehlednější hláška "přečíslováno od x po y čísel" než "přečíslováno xx čísel"

**Comment by zabak** [comment]
OK, ono je jedno co se tam napíše, takže ať je tam úplná informace: "Bylo přečíslováno n čísel počínaje číslem a, nově označeny x - y." Protože to že se změnila čísla 11-20 neznamená že těch čísel bylo 10.

**Comment by Kretiss** [comment]
@zabak Nasazeno na inqool testovacím serveru

**Comment by zabak** [comment]
Po funkční stránce je to v pořádku, prosím @BrozekAles a ostatní o vyjádření k textaci a způsobu zobrazení. Osobně  si myslím že by bylo lepší to zelené hlášení zobrazit uprostřed obrazovky, kde předtím bylo to okno s dotazem. Jinak bez připomínek.

**Comment by zabak** [comment]
@Kretiss nikdo nic nenamítá. Bylo by možné to zelené hlášení přesunout doprostřed obrazovky?

**Comment by Kretiss** [comment]
@zabak Nasadil jsem na test

**Comment by zabak** [comment]
funguje
