### ISSUE TITLE
Nefunguje tlačítko smazat exemplář

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#184]
nefunguje tlačítko smazat exemplář (číslo)

**Comment by annavandasova** [comment]
![image](https://user-images.githubusercontent.com/108134814/186613959-f7926a6c-b0e7-4ecf-b479-86141759a3f7.png)

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na našem testu, prosím o vyzkoušení.

**Comment by annavandasova** [comment]
@Kretiss prosím označovat odpovídajícími labely

**Comment by Kretiss** [comment]
@zabak

**Comment by zabak** [comment]
funguje
