### ISSUE TITLE
Vyhledávání svazků v přehledu exemplářů

### ISSUE THREAD

**Issue by BrozekAles** [NLCR/evidence.periodik#185]
V přehledu exemplářů se jednotlivé svazky dají najít jen přes datum, což není jednoznačné, protože v zadaném roce může být více svazků. Navrhuji tedy, aby kromě zadání data od do (vlevo nahoře) bylo možné zadat i čárový kód svazku.

**Comment by Kretiss** [comment]
@BrozekAles Nasazeno na našem testu, prosím o kontrolu.

**Comment by BrozekAles** [comment]
Ano, funguje, díky.

**Comment by BrozekAles** [comment]
V produkčním prostředí funguje
