### ISSUE TITLE
Co má dělat tlačítko "Duplicitní exemplář"?

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#186]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/811537/192969655-4403b637-782d-4b2d-86aa-d87c49da2150.png">

@annavandasova @korhon Teď se zobrazí formulář a když dám OK, tak to vyhodí chybu. Buď to má znamenat "duplikovat exemplář", nebo "duplikovat svazek". Pokud to první, tak se mi zdá že je v tom formuláři hodně nadbytečných informací a pokud to druhé tak není potřeba to tlačítko mít u každého čísla.

**Comment by ludvicekj** [comment]
obávám se, že to bylo pro tu první možnost "duplikovat exemplář" a je to pozůstatek dřívějšího zadávání dat (nakopírovalo to exempláře (čísla) v rozmezí uvedených datumů s danou signaturou a čk). a je to tedy nadbytečné.. 

otázkou je ještě, jestli zachovat i tlačítko vedle, "smazat exemplář". je to stejný pozůstatek, sice funguje, ale je otázkou, jestli mazání čísel nechceme nechat pouze v Editaci svazku..

**Comment by korhon** [comment]
Zrušil bych oboje

**Comment by zabak** [comment]
OK, zrušit

**Comment by zabak** [comment]
Vyřešeno, zavírám
