### ISSUE TITLE
ikonky fyzického stavu

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#187]
Pokud je zaškrtnutý checkbox Ověřeno (vyřešeno v issue #116), nezobrazují se správně ikonky fyzického stavu, resp. zobrazí se pouze zelená nebo šedivá ikonka s fajfkou. 

Ikonky byly kdysi dávno vytvořeny tak, aby v přehledové tabulce na prvního pohled ukázaly fyzický stav jednotlivého čísla: zelená fajfka - vše ok, šedá fajfka - ok s drobnými problémy (lze stále digitalizovat), blesk - problémy, vykřičník - chybějící strany. Pokud bychom chtěli toto zachovat, mělo by asi fungovat tak, aby se ikonka měnila podle nejhoršího stavu zaškrtnutého v checkboxech. 

Viz obrázky: 
1 - správně - vše ok, ikonka zelená fajfka 
3 - správně - nic nezaškrtnuto, ikonka oka upozorňuje na chybu ve vyplňování dat 

2 - špatně - oběma číslům chybí strany, měly by mít ikonu vykřičníku, ale pokud je zaškrtnuto Ověřeno je ikonka šedá fajfka, která by měla být pouze drobné problémy

![ikonky stavu 4 - kopie](https://user-images.githubusercontent.com/40558551/193039833-9e2b7c91-2dd5-4f7b-9f14-bf1fc844713d.png)
![ikonky stavu 4 - editace svazku - kopie](https://user-images.githubusercontent.com/40558551/193039841-bbc5fa22-5705-422d-b142-6fe426142ab0.png)

**Comment by ludvicekj** [comment]
ikony by v aktuálním nastavení měly mít tyto hodnoty: 

![image](https://user-images.githubusercontent.com/40558551/200862615-ecfe0ab8-8664-4216-bd75-9614274cef2a.png)


pokud bychom uvažovali o "semaforu" mohla by být podoba třeba takto: 

![image](https://user-images.githubusercontent.com/40558551/200864890-6b1efd00-899f-478d-82bb-d10dc2e2c221.png)

**Comment by zabak** [comment]
Souhlasím, ten semafor by byl lepší.

**Comment by Kretiss** [comment]
@zabak @ludvicekj nasazeno na testu

**Comment by ludvicekj** [comment]
při zaškrtnutí "chybí strany", by se mělo zobrazit červené kolečko.. 
![image](https://user-images.githubusercontent.com/40558551/203515059-9b397166-1f38-42ef-a36a-4c70c0b60b41.png)
![image](https://user-images.githubusercontent.com/40558551/203515628-0c458bf3-129f-4263-9fab-fafd669a0abd.png)

**Comment by Kretiss** [comment]
@ludvicekj Nasadil jsem opravu, zkuste to ještě jednou prosím

**Comment by ludvicekj** [comment]
funguje, děkuji..

**Comment by ludvicekj** [comment]
na produkci funguje
