### ISSUE TITLE
možnost označit celé sloupce

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#188]
V případě problému jako Nečitelně svázáno nebo Degradace, které zpravidla provázejí celý svazek, by bylo užitečné mít možnost označit celý sloupec.

**Comment by Kretiss** [comment]
@barinovak Nasazeno na testu

**Comment by zabak** [comment]
@Kretiss když zascrolluju dolů, tak ty dva upravené sloupce jedou nahoru včetně záhlaví

<img width="356" alt="image" src="https://user-images.githubusercontent.com/811537/200065424-3c46d764-7891-4875-85cb-48dbda9e7216.png">

**Comment by Kretiss** [comment]
@barinovak @zabak Opraveno na testu

**Comment by zabak** [comment]
Je to opraveno naopak než by bylo praktické. Předtím záhlaví neujíždělo nahoru, jen dvě položky ano, teď ujíždí celé, takže není jasné co který sloupec znamená.

**Comment by Kretiss** [comment]
@zabak Opraveno, bylo to způsobeno tím novým splitem stránky.

**Comment by annavandasova** [comment]
funguje
