### ISSUE TITLE
Fasety - úprava

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#190]
- [x] umožnit aby se dalo kliknout u faset na počty výskytů, nejen na název fasety
- [x] Mutační vydání - změnit text "bez názvu" na "bez označení"
- [x] V tabulce Editace vstupních dat místo prázdného řádku do Mutačního vydání dát volbu "bez označení"

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu

**Comment by zabak** [comment]
funguje
