### ISSUE TITLE
Znepřístupnit editaci záznamu pro nepřihlášeného uživatele

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#191]
Ve #171 se znemožnila editace svazku, ale zůstala zachovaná možnost "jakoby" Editovat svazek. Prosím o znemožnění editace pro nepřihlášeného uživatele.

**Comment by ludvicekj** [comment]
jestli to chápu správně, aby nepřihlášení nemohli vůbec vstoupit do Editace svazku, nebo aby jim zmizela ikonka? nechtěli jsme nechat přístup do Editace svazku i pro nepřihlášené proto, aby viděli podrobný přehled svazku?

**Comment by zabak** [comment]
@ludvicekj vidět ho mohou, ale proč je nechat "jako" editovat formulář, když ho stejně neuloží.

**Comment by ludvicekj** [comment]
@zabak když nejsem přihlášen, na testu i na produkce je všechno šedé a upravovat nic nejde.. 
![image](https://user-images.githubusercontent.com/40558551/196941356-a3d9fc3c-4b88-42fb-ada6-069f80aaac4d.png)

ale nějak "osekaná" tabulka by se mohla vedle kalendáře objevit v rámci badatelské aplikace..

**Comment by zabak** [comment]
@ludvicekj Tahle stránka je OK, problém jsou ty ostatní dvě (přehled a editace záznamu)

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu, prosím o kontrolu, jestli jsou v pořádku všechny stránky

**Comment by zabak** [comment]
ano, vyřešeno, je možné nasadit na produkci

**Comment by zabak** [comment]
funguje, zavírám
