### ISSUE TITLE
Nekonzistence v datech na produkci 

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#192]
Nově zadávaná data se nezobrazují v kalendáři. Československý sport 1966 se ale zobrazuje. Bude potřeba analyzovat existující struktury v solru a rozhodnout, jestli je možné některé duplicitně uložené údaje odstranit a kalendář nasměrovat tam, kde ta data jsou.

**Comment by Kretiss** [comment]
@zabak napíšu zde co jsem dohledal.

1) Do issue v solru se podle mě ukládaly data ze stránky https://permonik.inqool.cz/permonik/issue/179E787DAD07ED83A29C1612FF3914BDBA5E36C0. Vytvořilo se issue, které v sobě mělo pole exemplářů z pravé části stránky. 
Struktura byla následující:
<img width="485" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/199979571-9462320e-ef81-46f2-b81b-04718ce38c45.png">
Tyto issue se potom používaly v kalendáří a na základě toho pole exemplářů v issue se vypisovaly do kalendáře. 

2) Časem se to ale nějak změnilo a teď se ze stránky z bodu 1 ukládají data do tabulky exemplar, na issue se vůbec nesahá. Kalendář doteď tahal data z tabulky issues. Když jsem změnil endpoint na exempláře, objevily se v kalendáři všechny data, akorát špatně sjednocené, protože je každý exemplář zvlášť. 
Struktura exempláře:
<img width="624" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/199982987-648c1b86-7b81-4611-9c97-2ae3d934843d.png">
Na screenu jde vidět atribut id_issue, ten se ale generuje při vytváření exempláře z jeho id, tedy čárového kódu.

Ukázka roku 1953, červenec:
<img width="1680" alt="obrazek" src="https://user-images.githubusercontent.com/74928322/199986011-76dba256-69ec-4948-a7e2-6ec312f27a2d.png">

3) Zkoušel jsem na localhostu odstranit issue jádro ze solru a aplikace fungovala správně i bez něj, je potřeba to ale dobře vyzkoušet. Z pohledu frontendu by se z tama ale neměly tahat žádné data, pokud jsem našel všechno.

Abych to shrnul, dám na test tuto upravenou verzi, s tím, že kalendář bude zobrazovat data neseřazeně a vyhodím ze solru issue jádro. Tímto bych toto issue uzavřel a řešil kalendář dále v jeho issue, issue jádro na produkci kdyžtak vyhodím při dalším nasazení.

**Comment by zabak** [comment]
@Kretiss souhlasím. 
Prosím všechny o otestování funkčnosti na testu, hlavně to, jestli vidíte všechna data, že když něc uložíte, tak se to doopravdy uloží apod.

**Comment by zabak** [comment]
Protože se nikdo neozval a mě to funguje, tak posouvám dál.

**Comment by annavandasova** [comment]
prosím otestovat všechny!
