### ISSUE TITLE
Nekonzistentní chování faset

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#194]
Pokud vyberu Československý sport tak se mi automaticky zobrazí ve fasetě rozsah roků 1953 - 1989. Pokud přepíšu rok 1953 na 1966 a dám enter, tak se v aktivních filtrech zobrazí 1953 - 1989 a poté co se natáhnou data ze serveru, tak se aktivní filtr změní na 1966 - 1989. To je dívné chování, mělo by se rovnou zobrazit to co bylo zadáno, tj. 1966 - 1989.

Když pak přejdu na hlavní stránku a znovu zvolím Československý sport, tak se mi zobrazí ve fasetě to 1966 - 1989 a odpovídající čísla (ale aktivní filtr není), ale na pozadí se spustí dotaz bez filtrů a po chvíli se faseta změní na 1953-1989 a zobrazí se všechno. 

Tohle chování je obecné, platí pro všechny fasety. Systém by si měl buď pamatovat aktivní filtry nastavené pro jednotlivé metatituly a když se na daný. metatitul v rámci jedné session vrátím, tak ty filtry zachová, nebo by měl rovnou při novém příchodu na metatitul nebo jiné změně faset zobrazit až ty správné výsledky, ne ty předchozí nakešované.

**Comment by Kretiss** [comment]
Mělo by to být vše opraveno, upravil jsem filtry, ale by se ně nedalo klikat pokud se načítají data a opravil část kódu, co obstarávala ty requesty. Bylo tam dost chyb, ten request běžel na pozadí i pokud se přešlo na jinačí část aplikace a blokoval ostatní requesty, které byly ve frontě.

**K totomu bych měl dotaz**
Máte v plánu produkci nasazovat pod nějakou doménou? Bylo by vhodné tam mít SSL certifikát (teď si komunikaci může odchytnout kdo chce) + HTTP/2 (více vláken pro requesty -> HTTP/1.1 jede sekvenčně). HTTP/2 je vázané na HTTPS, takže to bez SSL certifikátu nepojede

**Comment by zabak** [comment]
@Kretiss nerozumím otázce. produkce jede na https a http/2

**Comment by Kretiss** [comment]
@zabak Jo já jsem si neuvědomil, že vy tam chodíte přes doménu.. my jsme totiž dostali IP adresu. V tom případě by bylo dobré tohle blokovat, aby se tam dalo dostat jenom skrze doménu

**Comment by zabak** [comment]
Požadavek na blokaci přístupu přes IP adresu - viz #197
Issue samotné je možné nasadit na produkci

**Comment by smallcubes** [comment]
@Kretiss přes jakou IP adresu na Permonika chodíte? Máte na mysli interní 10.x.x.x nebo veřejnou 195.x.x.x?

**Comment by Kretiss** [comment]
@smallcubes Mám namysli veřejnou

**Comment by zabak** [comment]
funguje
