### ISSUE TITLE
metatituly na úvodní stránce

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#196]
na produkci (permonik.nkp.cz) se zobrazují všechny metatituly. s @annavandasova jsme je tříbili před minulou schůzkou (nebyl zobrazen žádný, dávali jsme k zobrazení ČS sport, Svobodné slovo, ..). 

prosím, podívala by ses, jak to vypadá v nastavení metatitulů. 

![image](https://user-images.githubusercontent.com/40558551/198307581-eb5041b8-6346-4f04-9127-8c6fa4842638.png)

**Comment by annavandasova** [comment]
Teď jsem odendala MF testovací. A už se mi to nezobrazuje, prosím @ludvicekj vyzkoušet.
Ostatní chceme taky skrýt? Při včerejší diskuzi s kolegou z VHU mě informoval, že "už se koukal, jaká periodika tam zatím máme zadaná" - je to pro ně vodítko - co myslíš @zabak ?

**Comment by ludvicekj** [comment]
nezobrazuje, díky. ostatní tam mohou asi zůstat, jestli nevadí, že jsou prázdná.. 

-----Original Message-----
From: annavandasova ***@***.***> 
Sent: Thursday, November 3, 2022 1:09 PM
To: NLCR/evidence.periodik ***@***.***>
Cc: Ludvíček Josef ***@***.***>; Mention ***@***.***>
Subject: [*Newsletter*] Re: [NLCR/evidence.periodik] metatituly na úvodní stránce (Issue #196)

Teď jsem odendala MF testovací. A už se mi to nezobrazuje, prosím @ludvicekj <https://github.com/ludvicekj>  vyzkoušet.
Ostatní chceme taky skrýt? Při včerejší diskuzi s kolegou z VHU mě informoval, že "už se koukal, jaká periodika tam zatím máme zadaná" - je to pro ně vodítko - co myslíš @zabak <https://github.com/zabak>  ?

**Comment by zabak** [comment]
Já myslím, že by tam mohly zůstat, byť s nulovým obsahem. Aspoň naznačíme ostatním, co má případně smysl zadávat. Ale vzhledem k tomu, že to bude ještě mnoho let prázdné, tak se nic nestane, když se to taky skryje, alespoň do doby než uděláme alespoň import z Krameria.
