### ISSUE TITLE
Blokace přístupu přes IP adresu na produkci

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#197]
@annavandasova Na základě diskuse v https://github.com/NLCR/evidence.periodik/issues/194#issuecomment-1290728582 prosím o zařízení zablokování přístupu na produkci přes IP adresu (bude možný přístup jen přes permonik.nkp.cz)

**Comment by smallcubes** [comment]
@Kretiss zkoušel jsem `https://195.113.132.121/` a dostanu `404`

**Comment by Kretiss** [comment]
@smallcubes Jde se tam dostat pod http a portem 8080. http://195.113.132.165:8080/permonik/home

**Comment by smallcubes** [comment]
@Kretiss přístup by už neměl být funkční

**Comment by annavandasova** [comment]
Také mi už nefunguje. Přístup přes http://10.1.20.49:8080/permonik/home chceme ponechat? @zabak @smallcubes

**Comment by zabak** [comment]
To je z vnitřní sítě NK, ale nedává smysl aby tam byl, takže ho klidně nech zaříznout.

**Comment by annavandasova** [comment]
@smallcubes prosím o zařízení

**Comment by smallcubes** [comment]
V současné není vhodné požadavek provést (viz e-mail).

**Comment by annavandasova** [comment]
@smallcubes jak to prosím je nyní?
