### ISSUE TITLE
Permonik na produkci mimo provoz

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#199]
Permonik je spadený, po delší době nečinnosti se jen zobrazí generická chybová stránka nginx

**Comment by Kretiss** [comment]
Toto už jsem řešil s @StastnyP, měl by někomu od vás napsat mail, protože nevím, z kama se ta chyba vzala a nestalo se to po nasazení, objevilo se to někdy potom.. navíc, permonik běží na Apache-tomcat, ta chyba musí jít z někama jinama.

**Comment by zabak** [comment]
Takže problém je na straně NK.

**Comment by annavandasova** [comment]
Už jsem zadala ticket na servicedesku NK

**Comment by smallcubes** [comment]
@Kretiss zkoušel jsem zadat příkaz na serveru: `$ curl -vL http://127.0.0.1:8080/permonik/home`, ale zůstanu viset.

**Comment by smallcubes** [comment]
Po restartu se nic nezměnilo '# systemctl restart tomcat'

**Comment by Kretiss** [comment]
@smallcubes to jsem dělal taky, já myslel restart celého serveru

**Comment by smallcubes** [comment]
@Kretiss už se to probralo

**Comment by annavandasova** [comment]
ano, funguje, zavírám
