### ISSUE TITLE
Nelze uložit svazek

### ISSUE THREAD

**Issue by simeckovaj** [NLCR/evidence.periodik#200]
Opakovaně mám problém s uložením svazku. Když kliknu vlevo na Uložit celý svazek, tak se neuloží a vyskočí na mě okno, že čárový kod je povinný. Ale ten tam mám, zkusila jsem i variantu, jestli v něm není mezera, ale i když ho vypíšu ručně nebo načtu čtečkou, stejně se mi nedaří ukládat.

![obrazek](https://user-images.githubusercontent.com/117838502/200862636-31776884-51fc-48e9-aa0e-0c2733ce346a.png)

**Comment by ludvicekj** [comment]
napadá mě, že by problém mohl být v písmeně A v čárovém kódu a aplikace vyžaduje čistě číselnou hodnotu?

**Comment by simeckovaj** [comment]
Pravda, předchozí svazek, který jsem ukládala, měl čárový kod bez A, ale čk s A už je v aplikaci uložený, např. 265A005341

**Comment by Kretiss** [comment]
@simeckovaj @ludvicekj Je to tak, píše to tuto hlášku, protože se v kódu nachází písmeno.

**Comment by zabak** [comment]
Prosim o upravu teto kontroly tak aby slo jen o varovani, ktere lze prekonat. Jak co do obsahu tak co do delky kodu.

**Comment by annavandasova** [comment]
musí zde být uveden identifikátor konkrétního svazku

**Comment by annavandasova** [comment]
musí zde být uveden identifikátor konkrétního svazku

**Comment by Kretiss** [comment]
Nasadil jsem na test opravu

**Comment by simeckovaj** [comment]
Problém trvá, stále se mi nedaří uložit svazek s čárovým kodem s písmenem A, a to ani pod jiným účtem - testovali jsme i z účtu Kristýny Bařinové. Svazek s čk jen s číselnými znaky uložím bez problémů.

**Comment by Kretiss** [comment]
@simeckovaj Zkoušeli jste to na testovacím prostředí? Na produkci to zatím ještě není nasazené. Viz https://permonik.inqool.cz/permonik/svazek/12345AAa, vytvořil jsem svazek i s písmeny.

**Comment by simeckovaj** [comment]
Omlouvám se, v testovacím prostředí funguje a uloží se, s upozorněním, že čárový kod obsahuje text.

**Comment by annavandasova** [comment]
otestovat @simeckovaj

**Comment by simeckovaj** [comment]
Funguje bez problému na testu i na produkci. 
Upozorňuje, že čk obsahuje text a poté, že svazek byl úspěšně uložen.
