### ISSUE TITLE
Přehled svazku uvádí špatné údaje

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#202]
Tabulka přehled svazku uvádí špatné údaje - př. špatný rozsah čísel

**Comment by ludvicekj** [comment]
![špatný rozsah čísel v přehledu svazku](https://user-images.githubusercontent.com/40558551/201062860-9b1e14ba-fe01-421f-9eed-d2f3864d04c6.png)

**Comment by annavandasova** [comment]
na testu i na produkci funguje špatně

**Comment by annavandasova** [comment]
doplnit do přehledu svazku chybějící čísla

**Comment by annavandasova** [comment]
přehled svazku musí být jen danému čk

**Comment by Kretiss** [comment]
@annavandasova @zabak Tahalo to navíc data neexistujících exemplářů, to řeší část problému. Trochu větčí problém ovčem nastává s rozsahem čísel. V tabulce editace vstupních dat se to tahá ze svazku, v této přehledové tabulce se to tahá z exemplářů a ty mají atribut číslo daný jako string a ne int, takže to ty stringy špatně porovnává. Nabízí se tady teda dvě možnosti, a to buď překopat celou databázi a opravit tuto chybu a nebo to přestat tahat z faset a spočítat to na frontendu ručně. Za mě bude rozumnější ta cesta počítání ručně, protože jakmile změním typ atributu v solru, přestane fungovat, takže by se to muselo řešit nějakým složitým skriptem, který by to upravil

**Comment by zabak** [comment]
@Kretiss teď jděme tou jednodušší cestou. Pokud se budou dělat změny databáza, tak se to dá předpokládám upravit.

**Comment by Kretiss** [comment]
@annavandasova @zabak Nasazeno na testu, prosím o kontrolu

**Comment by annavandasova** [comment]
Za mě v pořádku, prosím o kontrolu i někoho dalšího

**Comment by zabak** [comment]
Funguje

**Comment by annavandasova** [comment]
Posílám zde chybu:
![image](https://user-images.githubusercontent.com/108134814/219366390-b1970e46-2f30-44f8-8c15-2e1072c8a37b.png)

Ale vyplněno je:
![image](https://user-images.githubusercontent.com/108134814/219366551-8a60db03-5445-43a1-a348-654f3da39f47.png)

**Comment by Kretiss** [comment]
@annavandasova @zabak Nasazeno na vašem testu

**Comment by annavandasova** [comment]
Stále podle mě nefunguje správně - př:
![image](https://user-images.githubusercontent.com/108134814/226617815-b20057f4-b348-408e-b5d3-2ce6193bcc8a.png)
zde píše fyzický stav "vyhovující", ale svazek je "nekontrolován" (bílé kolečko)

**Comment by korhon** [comment]
Stav ověřeno se nejspíš ukazuje jako typ poškození
![obrazek](https://user-images.githubusercontent.com/33937374/226917974-e785eb5f-383f-4eae-a9a7-19973bfbb8ab.png)

**Comment by annavandasova** [comment]
Ověřeno přesunout výše do kategorie ověřeno a rozdělit ano/ne s počty

**Comment by Kretiss** [comment]
@korhon @annavandasova Nasazeno na produkci. Fyzický stav jsem ponechal tak jak je, protože se doposud odvíjel jenom od stavů svazku, jako jsou poškozené strany, chybně svázáno atd. Odpovídá to tím pádem fyzickému stavu a jestli jsou čísla zkontrolována nebo ne jde teď vidět pod Ověřeno: ano/ne
