### ISSUE TITLE
Našeptávání názvů a podnázvů při editaci titulu

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#205]
Když zadávám v editaci svazku tabulku denních vydání, měl by systém našeptávat název a podnázev podle už vložených čísel metatitulu. 
V detailním popisu svazku by to mělo našeptávat to co obsahuje tabulka denních vydání a to co už bylo vloženo v rámci svazku, v případě příloh názvy příloh z celého metatitulu.

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu.

**Comment by zabak** [comment]
V tabulce denních vydání to funguje, ale zcela to chybí v detailním popisu svazku. Prosím o doplnění.

**Comment by Kretiss** [comment]
@zabak Nasazeno na testu

**Comment by zabak** [comment]
funguje

**Comment by annavandasova** [comment]
funguje
