### ISSUE TITLE
přílohy 

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#206]
Přílohy musí mít číslování ve vlastním sloupci „Číslo přílohy“.
![image](https://user-images.githubusercontent.com/40558551/201071386-56ef4aff-ca68-4efa-9748-159c0cc4eec0.png)
 

Informaci o tom, že toto příslušné vydání je příloha a patří do jiného sloupce, dosáhneme tím, že v „Tabulce denních vydání“ zřídíme dva nové typy vydání "Příloha" pro zvláštní nepravidelné přílohy a "Pravidelná příloha" pro pravidelné přílohy - toto označení založí paralelní číslování pouze pro pravidelné přílohy. 
![image](https://user-images.githubusercontent.com/40558551/201071435-3dd562a0-e52a-4714-aacb-a1acd9e99937.png)
 

Zápis musí umožnit průběžné zpracování, aby průzkumník nemusel listovat dopředu a dozadu. To by vytvářelo prostor pro chyby. Proto pokud jsou přílohy u čísla, kdy vyšly, tak musí být v editaci svazku na tomto místě. Pokud jsou svázané na konci, pak musí být na konci. 
V Tabulce denních vydání by tedy měl být přepínač nebo checkbox, který při generování struktury buď ponechá přílohu u dne, kdy vyšla, nebo je hromadně seřadí na konci svazku.
![image](https://user-images.githubusercontent.com/40558551/201071544-bbe45aff-4412-427d-9773-095e174c79cc.png)
 

V tabulce „Detailní popis svazku“ by bylo vhodné 
-	řádek s přílohou barevně odlišit,
Problematické je zpracování a provázání příloh, které jsou ve zcela samostatném svazku. Ty by se měly vložit jako běžné svazky, ovšem v ideálním případě by měly odkazovat vazbu na metatitul a odkaz na čarový kód, ke kterému patří. Jak je v Permonikovi zobrazovat, je otázka. Stejně tak může působit problémy změna čárového kódu u kteréhokoliv ze svazků.

**Comment by zabak** [comment]
Funguje, jen prosím v tabulce denních vydání generovat čísla příloh od 1 místo od 0 a číslovat samostatně přílohy a pravidelné přílohy.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/811537/211027218-039b2e18-830f-434a-8bb4-6edc800836e3.png">

**Comment by annavandasova** [comment]
Nelze editovat číslo přílohy v Detailním popisu svazku - prosím opravit

**Comment by Kretiss** [comment]
@zabak @annavandasova Nasazeno na testu, editace čísla přílohy mi funguje

**Comment by zabak** [comment]
funguje

**Comment by ludvicekj** [comment]
myslím, že funguje správně. 
ale před uzavřením bychom se měli ještě dohodnout na opravě již zadaných dat.. :-(

**Comment by annavandasova** [comment]
úkol @Kretiss sjednotit názvy příloh - př. VOLNO, volno, Volno - vždy bude jako Volno

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na produkci

**Comment by Kretiss** [comment]
Číslo a číslo přílohy se přečíslovává zvlášť

**Comment by AlesBrozek** [comment]
Nevidím nikde možnost přečíslování přílohy. Dne 3.4. vyšla příloha č. 13 (ručně jsem změnil) a potřebuji, aby automaticky u data 10.4. měla příloha č. 14
![Snímek obrazovky 2024-10-10 v 9 47 30](https://github.com/user-attachments/assets/ae2f4d53-5aee-4a2e-bf84-a730db062698)

**Comment by Kretiss** [comment]
@AlesBrozek Zkuste teď prosím, opravil jsem

**Comment by AlesBrozek** [comment]
Ano, teď už přečíslování příloh funguje, díky, ale objevil se problém příloh, které nevyšly v pravidelný den, viz #256

**Comment by Kretiss** [comment]
@ludvicekj @annavandasova @zabak @AlesBrozek zavírám tím pádem toto issue, pokračovat se bude v issue https://github.com/NLCR/evidence.periodik/issues/256
