### ISSUE TITLE
Duplikovat šablonu pro editaci svazku

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#207]
Při editaci svazku umožnit zduplikovat šablonu (tabulky editace vstupních dat a denních vydání) s možností tu zduplikovanou šablonu ručně doeditovat jako by byla vytvořená ručně.

**Comment by StastnyP** [comment]
1. Zduplikovat celý svazek (levá i pravá strana)
    2. Při duplikaci smazat tyto atributy - čárový kód, signatura, vlastník (lze nastavit automaticky podle toho kdo je aktuálně přihlášen), mutační vydání
    3. Tlačítko duplikovat - v detailu svazku, vedle “Smazání celého svazku”
    4. Potvrzovací tlačítko vygenerovat, uloží svazek do databáze

**Comment by zabak** [comment]
- [ ] Když zduplikuji svazek, očekávám že budu v tom novém, zduplikovaném svazku, ne v tom původním - to je správně. Pak ho doplním, uložím a jsem zpět v tom původním. Bylo by to možné změnit? Očekával bych že zůstanu v tom novém. 
- [ ] Navíc: vlastník by měl být nastaven automaticky podle toho, ke které knihovně přísluší uživatel, který záznam vytváří.

**Comment by Kretiss** [comment]
@zabak První bod je opraven, druhý musím dodělat spolu s těmi vlastníky, kteří jsou v jiném issue

**Comment by zabak** [comment]
Když zduplikuji svazek, tak se do prvního čísla vyplní nula a do posledního čísla -1. Měla by tam být stejná čísla jako ve svazku, ze kterého jsem duplikoval.

**Comment by Kretiss** [comment]
@zabak Zkousel jsem to teď u sebe i na testu a nestalo se mi to, mělo by to při duplikaci zůstat stejné jako v původním svazku. Každopádně jsem zjistil, že to posledni_cislo nemá reálně žádný význam a je tam jenom jako informace, které číslo ve svazku je poslední (vyplňuje se to automaticky při ukládání). Prvni_cislo je potom používáno pro začátek číslování exemplářů.

**Comment by zabak** [comment]
už mi to funguje

**Comment by annavandasova** [comment]
@zabak otestuješ prosím?
