### ISSUE TITLE
Filtrace při úpravách detailního popisu svazku

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#208]
Mít možnost podobně jako v excelu zapnout v jednotlivých sloupcích tabulky filtry. Např. podle mutace, vydání, názvu apod. Pokud je nějaký filtr aktivní, tak funkce přečíslování směrem dolů by se měla aplikovat jen na viditelné řádky (např. jen na přílohy)

**Comment by annavandasova** [comment]
a mutační vydání

**Comment by annavandasova** [comment]
funkce filtrování bez přečíslování

**Comment by annavandasova** [comment]
nadefinovat, co všechno filtrovat: mutace, vydání, název, podnázev, mutační vydání. Filtrování jako v excelu.

**Comment by StastnyP** [comment]
Filtrace podobně jako v excelu, nad záhlavím zobrazit tlačítko s filtrem. Identifikátor, pokud je filtr aktivní.

**Comment by annavandasova** [comment]
až nová aplikace

**Comment by Kretiss** [comment]
Vypsat co všechno chcete filtrovat a jak se vyfiltrovaná data mají chovat (například hromadné úpravy atd)

**Comment by Kretiss** [comment]
@zabak @annavandasova bude se filtrovat tedy jenom podle mutace, vydání, název, podnázev, mutační vydání?

**Comment by annavandasova** [comment]
@Kretiss filtrovat podle mutace, vydání, název, podnázev, mutační vydání

**Comment by Kretiss** [comment]
@annavandasova @zabak prosím otestovat

**Comment by Kretiss** [comment]
V pořádku
