### ISSUE TITLE
Přechod z editace svazku na přehledovou tabulku

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#210]
Bylo by vhodné, aby se při návratu do přehledové tabulky z tabulky editace svazku, zobrazil právě editovaný rok. V současné chvíli se vždy vrátí na začátek, tedy na první rok, který je v Permonikovi v daném titulu zpracován.

**Comment by Kretiss** [comment]
@barinovak @zabak Pozměnil jsem teď dost věcí. Aktuálně aplikace funguje tak, že při každém vybrání filtru nebo stránky upraví url adresu, tzn. že při návratu ze svazku je adresa třeba následující: https://permonik.inqool.cz/permonik/result/2081c9cc60d1101b53c4a0ce348195ee?nazev-0=%C4%8Ceskoslovensk%C3%BD%20sport&mutace-1=Praha&znak_oznaceni_vydani-2=%E2%96%A0%E2%96%A0&vlastnik-3=NKP. Aplikace si z url adresy zpracuje použité parametry a zrovna je aplikuje, takže se načtou předchozí použité hodnoty v přehledové tabulce. 

Další změnou je postupné načítání exemplářů. Výchozí délka přehledové tabulky je 50 řádků, tzn. že těchto 50 řádků je načtených z databáze a při každém dalším posunu stránky v tabulce se načítají nové data, takže jsou načítání rychlejší a nenačítají se zbytečná data, jako tomu bylo do teď (prvotní načtení tabulky muselo tahat třeba 15MB dat, teď je to pár desítek KB).

Další věc je, že se výchozí počet řádků v tabulce drží po dobu běhu aplikace, takže pokud si to někdo nastaví na 500, dokud aplikaci nezavře, bude se mu při každé návštěve přehledové tabulky načítat 500 řádků.

**Comment by zabak** [comment]
funguje

**Comment by annavandasova** [comment]
Prosím otestovat @barinovak

**Comment by annavandasova** [comment]
funguje
