### ISSUE TITLE
Pomalé odezvy administrace

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#211]
Nastavovala jsem jako administrátor jednotlivé vlastníky u uživatelů a systém má poměrně pomalou odezvu - když kliknu na uložit, tak to celkem trvá, než se změna uloží. Nejde s tím něco udělat?

**Comment by Kretiss** [comment]
Taky jsem si toho všiml, ale dělá to jenom na produkci. Zatím nevím, čím to může být..

**Comment by Kretiss** [comment]
@annavandasova Zatím se mi na to nepodařilo přijít, ale upozorňuji, že produkci je využito 94% disku
