### ISSUE TITLE
Smazat vykřičníky u tlačítek 

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#213]
Prosíme smazat vykřičníky u tlačítek v editaci vstupních dat

![image](https://user-images.githubusercontent.com/108134814/218106681-7258f2d6-8c32-450e-8d85-f410337e8b45.png)

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na vašem testu

**Comment by Kretiss** [comment]
@annavandasova můžete zavřít úplně
