### ISSUE TITLE
chybí čárový kod - nelze editovat

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#214]
Po uložení editovaného svazku Čsl. Sport 1978 se v přehledové tabulce svazek vygeneroval bez čárového kodu a není možné jej v současné chvíli znovu upravovat, ani otevřít.
![Snímek obrazovky 2023-02-17 122343](https://user-images.githubusercontent.com/40160250/219645080-0bc0204c-389a-4acb-81f3-5066fdc2ec19.jpg)

**Comment by annavandasova** [comment]
svazek smazat

**Comment by annavandasova** [comment]
prosím smazat

**Comment by barinovak** [comment]
prosím smazat vadný svazek @Kretiss

**Comment by Kretiss** [comment]
@annavandasova @barinovak Můžu poprosit o čárový kód, který se měl tehda uložit? Smažu exempláře, ale svazek tam zůstane (předpokládám že se uložil)

**Comment by barinovak** [comment]
265A005194
