### ISSUE TITLE
duplikovat svazek

### ISSUE THREAD

**Issue by Chlupova** [NLCR/evidence.periodik#215]
chybne fungovani  - kopiruje se do predchoziho kopirovaneho svazku

**Comment by zabak** [comment]
Československý sport rok 1953, 3.1. jsou tam dva svazky, když rozhliknu ten co končí na 774 tak se mi zobrazí číslo z ročníku 1954.

**Comment by Kretiss** [comment]
@Chlupova @zabak Duplikování praveno
