### ISSUE TITLE
Ročník svazku

### ISSUE THREAD

**Issue by StastnyP** [NLCR/evidence.periodik#217]
- [ ] Přidat ročník v editaci vstupních dat
- [ ] Pouze jako popisná informace
- [ ] Formát - Arabské číslice, bez tečky

**Comment by annavandasova** [comment]
Přidat pod signaturu

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na produkci

**Comment by annavandasova** [comment]
Poprosím opravit na "Ročník"

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na produkci
