### ISSUE TITLE
Zvláštní vydání a Přílohy v označení vydání 

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#220]
![image](https://user-images.githubusercontent.com/108134814/231438250-b6d2e12c-8d93-48bb-ac13-3f4821efae6e.png)
V označení vydání prosíme o následující úpravy:
- "příloha" přejmenovat na "jiná příloha" a přeřadit to až za "pravidelná příloha"
- "zvláštní" vydání přejmenovat na "jiné"

**Comment by Kretiss** [comment]
@annavandasova Nasazeno na produkci
