### ISSUE TITLE
čísla příloh

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#224]
@Kretiss 

v Detailním popisu svazku nedojde při změně vydání na Pravidelná příloha nebo Jiná příloha editovat ke změně čísla do sloupce Číslo přílohy, ani jinak Číslo přílohy editovat.. 

![image](https://user-images.githubusercontent.com/40558551/236248511-d16c6eb2-e5b9-4304-bd9d-71f717e01b6e.png) 

k "odskočení" Příloh do vlastního sloupce ani k barevnému zvýraznění nedojde ani při nově/opětovně vygenerované tabulky. nedojde ani k seřazení přílohy na konec svazku při zaškrtnutí Přílohy na konci.. 

![image](https://user-images.githubusercontent.com/40558551/236462485-fdddf05a-fc88-430b-afd2-b2925e11ea19.png)

**Comment by Kretiss** [comment]
@ludvicekj Zkuste to prosím ještě po uložení, co to bude dělat

**Comment by Kretiss** [comment]
@ludvicekj Ikdyž asi máte pravdu, že to nebude fungovat. Tohle se muselo rozbít při migraci. Podívám se na to přístí týden

**Comment by Kretiss** [comment]
@ludvicekj Máte to nasazeno na produkci. Seřazení na konci svazku se projeví až po uložení (znovu načtení) svazku nebo při generování

**Comment by ludvicekj** [comment]
@Kretiss super, velice děkuji. vyzkoušel jsem, funguje.
