### ISSUE TITLE
řazení příloh

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#225]
Při editaci příloh se po uložení příloha automaticky předřadí před číslo, ke kterému se váže. Musí to být naopak, nejprve číslo a poté až příloha. @Kretiss 
 
![1 (2)](https://github.com/NLCR/evidence.periodik/assets/40160250/22439af0-3963-4c23-ba3f-b30747e05c9f)
![2](https://github.com/NLCR/evidence.periodik/assets/40160250/0a8dd190-f50e-4664-b019-f612ef7d2a74)

**Comment by Kretiss** [comment]
@annavandasova @barinovak Opraveno

**Comment by ludvicekj** [comment]
mělo by být v pořádku.
