### ISSUE TITLE
chybějící čísla v přehledové tabulce 

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#227]
v přehledové tabulce se zobrazují i čísla, která jsou v editaci svazku označena jako chybějící: 

![přehledová tabulka číslo chybí svazek](https://github.com/NLCR/evidence.periodik/assets/40558551/42f87d46-9d42-483f-bebb-e6a02d6b6603)
![přehledová tabulka číslo chybí](https://github.com/NLCR/evidence.periodik/assets/40558551/3204de6c-00a0-4ab0-9a91-e3f5c35b536f)

@Kretiss

**Comment by BrozekAles** [comment]
a navíc se u těchto chybějících čísel objevil v přehledové tabulce údaj "Ověřeno, poškozeno" viz prvních 16 čísel u svazku 314800329595

**Comment by Kretiss** [comment]
@ludvicekj @BrozekAles Opraveno

**Comment by BrozekAles** [comment]
@Kretiss dle mne to není opraveno, u svazku 314800329591 chybí č. 8, ale v tabulce viz printscreen to není rozeznatelné
![Snímek obrazovky 2023-06-27 v 10 19 48](https://github.com/NLCR/evidence.periodik/assets/7532753/de8b4f04-bda8-42ce-b537-ac35d43ebeff)

**Comment by Kretiss** [comment]
@BrozekAles Já to číslo tady nevidím, otevřel jste si tu aplikaci znovu?
<img width="1680" alt="obrazek" src="https://github.com/NLCR/evidence.periodik/assets/74928322/66f7301b-6bcf-4c1a-8c9e-fedd484a1733">

**Comment by ludvicekj** [comment]
mělo by být v pořádku. děkuji
