### ISSUE TITLE
Pole mutační vydání v detailním popisu svazku

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#230]
nutno rozšířit, aby byl vidět větší počet znaků

**Comment by zabak** [comment]
Nejen mutační vydání, stejný problém je i ve sloupci název a vlastně i podnázev. Pokud je v daném údaji chyba, která není na začátku, tak není na první pohled vidět. Možná by stačil jen tooltip, že by se při najetí kurzoru nad daný údaj zobrazil celý jeho text.
