### ISSUE TITLE
Odstranění prázdných mezer před a za vkládaným údajem

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#231]
Kvůli snížení chybovosti při vkládání údajů při editaci vstupních dat prosím o softwarové odstranění prázdných mezer před a za vkládaným údajem, než se uloží svazek.

**Comment by AlesBrozek** [comment]
Nechci vytvářet nové issue a jen připisuji, že by ke snížení chybovosti přispěla možnost pročišťovat našeptávač, který nabízí např. text podnázvu periodika v mnoha variantách včetně obsahujících překlepy

**Comment by AlesBrozek** [comment]
A taky by se hodilo, kdyby se odstraňovaly prázdné řádky u Detailního popisu svazku, které vznikly, když se omylem  nebo systémovou chybou vytvořil duplicitní záznam o výtisku v Detailním popisu svazku. Jedná se sice o kosmetickou úpravu Detailního popisu svazku, ale v případě velkého množství prázdných řádků je tabulka zbytečně roztahaná.

**Comment by zabak** [comment]
Pokud je od některého dne více řádků a některé z nich jsou prázdné, tak ty prázdné odmazat. Pokud v daném dni jsou jen prázdné řádky, tak jeden nechat.

**Comment by AlesBrozek** [comment]
Zdá se, že nebyly odstraněny prázdné mezery. Při prohlídce fasety Podnázev najdeme "deník Ústředního výboru ČSTV" na dvou místech

**Comment by annavandasova** [comment]
@Kretiss prosím o kontrolu

**Comment by Kretiss** [comment]
V nové aplikaci hotovo
