### ISSUE TITLE
Úpravy zpřístupňovací modul

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#234]
v detailním popisu svazku:

- [x] zneviditelnit tabulku „denních vydání“
- [x] tabulku vstupní data přejmenovat na „údaje o svazku“, zúžit ji a prodloužit dolů
- [x] zúžit sloupce (popis sloupců může být svisle)
- [x] ukotvit sloupec datum
- [x] doplnit do data den
- [x] zneviditelnit prázdné řádky – nechat pouze ty, kde je „je ve svazku“ a „číslo chybí“ – nezobrazí se dny, kdy periodikum vůbec nevycházelo

- [x] záhlaví stránky přejmenovat – nyní „periodik“ -> „Evidence periodik – badatelská aplikace“
- [x] zobrazení kalendáře bez barvy – barva zde nenese význam
- [x] v kalendáři umožnit posun na další měsíc šipkou (u „zobrazený měsíc“)

**Comment by Kretiss** [comment]
@annavandasova @zabak Prosím ještě o Vaší interní diskuzi ohledně té provázanosti tabulky a kalendáře, jak to má fungovat při přepínání z jednoho prostředí do druhého, jak jsme se bavili na meetingu, ať to můžeme doladit a odstranit ty bugy, které tam nastávají

**Comment by ludvicekj** [comment]
@annavandasova @zabak @Kretiss vzhledem k tomu, že jsem to nadnesl já, udělal jsem k tomu vedlejší issue #235

**Comment by annavandasova** [comment]
zúžit sloupce co nejvíce - zmenšit písmo, zalomit název sloupce

**Comment by zabak** [comment]
Radka připraví tabulku s kratičkými názvy a tooltipy

**Comment by Kretiss** [comment]
Doložit dokument s názvy

**Comment by annavandasova** [comment]
@Kretiss dokument s návrhy pošlu mailem

**Comment by Kretiss** [comment]
@annavandasova prosím otestovat. Názvy jsou dané pod sebou, můžeme kdyžtak ještě doupravit, ale držel bych se toho, jak je to teď navržené

**Comment by Kretiss** [comment]
V pořádku
