### ISSUE TITLE
fasety a zobrazení kalendář - tabulka

### ISSUE THREAD

**Issue by ludvicekj** [NLCR/evidence.periodik#235]
@annavandasova @zabak @korhon 
nechávám zde k nějaké diskuzi, jak bychom chtěli, aby to zobrazení vypadalo.. 

při zobrazení pomocí Tabulky jsou fasety podrobnější a lze pomocí nich filtrovat obsah, který se nezobrazí zpětně v kalendáři. zmizí i tlačítka na přepínání Kalendář - Tabulka. tlačítko Vymazat filtry funguje pro oboje zobrazení, tím jde se vrátit do výchozího stavu. tlačítko zpět v prohlížeči vrátí na domovskou stránku. 

myslím, že by určitě neměla mizet tlačítka Kalendář - Tabulka. a např. by se mohla pro tyto případy přidat k/místo textu "Nebyly nalezeny žádné exempláře" hláška "Pro dané hledání nejsou v tomto zobrazení výsledky, přepněte do Tabulky/Kalendáře). 

případně (nevím, jestli by bylo možné), aby, pokud se v jednom zobrazení něco vyfiltruje, se v druhém odskočilo na stejná data. (v tomto příkladě, pokud tabulka začíná daty od března 1962, aby se po návratu do kalendáře, nezobrazil leden 1953, ale taktéž březen 1962). 

respektive, jestli by nebylo dobře, rozšířit i fasety u kalendáře tak, aby navrhovaly filtrování pomocí všech dat z metatitulu (jako v Tabulce), místo jen pomocí zobrazeného měsíce. 

![fasety-tabulka](https://github.com/NLCR/evidence.periodik/assets/40558551/ac0e1db2-da45-442a-a723-0553f8df7370)
![fasety-kalendář](https://github.com/NLCR/evidence.periodik/assets/40558551/8fd3b70e-df58-4bb7-a26b-64056cefc6ab)
![fasety-kalendář-2](https://github.com/NLCR/evidence.periodik/assets/40558551/95cfb21a-d409-449f-9216-4571d6ede0e5)

**Comment by annavandasova** [comment]
souhlasím

**Comment by ludvicekj** [comment]
z minulé diskuze vyplynulo tedy toto @Kretiss: 

- [ ] tlačítka Kalendář - Tabulka by měla být stále viditelná bez ohledu na to, co se na dané stránce zobrazí 
- [ ] pokud nelze žádná data zobrazit, místo "Nebyly nalezeny žádné exempláře" hláška "Pro dané vyhledávání nelze zobrazit žádné výsledky. Prosím, upravte parametry vyhledávání." 
- [ ] fasety pro zobrazení v Kalendáři i Tabulce by měly být stejné z celého metatitulu (teď je možné v Kalendáři vyhledávat pouze ve fasetách pro daný měsíc, ale mělo by jít z celého metatitulu jako v Tabulce) 
- [ ] zobrazená data by měla zůstat stejná při přechodu mezi Kalendářem a Tabulkou. pokud prohlížím v Kanlendáři září 1962 a přepnu do Tabulky, mělo by odskočit taktéž na září 1962, a naopak.. a také, pokud fasetami v jednom zobrazení zpřesním vyhledávání, mělo by druhé označené fasety respektovat a zobrazit stejná data.

**Comment by Kretiss** [comment]
Synchronizovat roky

**Comment by Kretiss** [comment]
@ludvicekj @annavandasova Prosím otestovat

**Comment by annavandasova** [comment]
funguje
