### ISSUE TITLE
Skok na správné číslo z výsledků vyhledávání

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#239]
Když například si v ČS Sportu vyhledám vydání s dvěma šeticípými hvězdičkami, tak se vyborou dvě čísla, např. 67 a 68. Když ale pak kliknu na svazek, abych je upravil, tak se dostanu na začátek svazku. Cílem je, abych byl svazek nalistovaný tak, aby byl uživatel hozený rovnou příslušné číslo.

**Comment by Kretiss** [comment]
@zabak funguje na testu pro přihlášeného uživatele, který má možnost editovat. Bohužel to nescrolluje doprostřed tabulky, řádek se zobrazí až na konci. V knihovně to není naimplementováno hezčím způsobem. Mají to v plánu, ale zatím bez nějakého data implementace. https://github.com/mui/mui-x/issues/4013
