### ISSUE TITLE
Časová razítka při aktualizaci dat 

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#240]
Zřídit pro záznam čísla časové razítko poslední aktualizace. Pokud dojde k aktualizaci údajů o čísle, aktualizovat časové razítko. Nastavit u existujících záznamů čísel aktuální datum jako "počátek"

**Comment by annavandasova** [comment]
abychom věděli, jak jsou data aktuální, kdy byly provedeny změny

**Comment by Kretiss** [comment]
@zabak Tady se nám jedná teda jenom o to, aby exemplář a svazek měl údaj o poslední změně?

**Comment by zabak** [comment]
Základ je opravdu informace o tom, kdy došlo k poslední aktualizaci (a raději i kým). To se možná dá vytáhnout ze Solru už teď...? Vyšší stupeň by bylo nějaké logování změn, třeba cestou pravidelných exportů celé databáze do nějakého textového formátu, třeba do jsonu. To bych ale nechal na samostatné issue.

**Comment by Kretiss** [comment]
@zabak momentálně je tam jenom časový údaj, který slouží ale hlavně interně pro Solr, takže bych na to udělal stejně atribut zvlášť. Uživatel tam není vedený vůbec

**Comment by zabak** [comment]
OK

**Comment by Kretiss** [comment]
@zabak Přidal jsem sledování, ale na FE to není nikde vidět. 

<img width="498" alt="obrazek" src="https://github.com/user-attachments/assets/00265672-acf3-41c3-bd0f-938bb424d407">

Zavírám tedy s tímto komentářem
