### ISSUE TITLE
Duplikace svazku

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#241]
Při použití tlačítka "duplikace svazku" je nutné, aby zůstaly z tabulky "editace vstupních dat" informace o metatitulu a vlastníkovi, tabulka denních vydání zůstává zachována a v tabulce detailní popis svazku se pak duplikovala pouze vygenerovaná struktura duplikovaného svazku, ale prázdná, bez kopírování zatržených defektů z původního svazku.

**Comment by annavandasova** [comment]
chceme ji v nové aplikaci?

**Comment by annavandasova** [comment]
pokud chceme, tak potřeba přesně vypsat atributy , které chceme kopírovat z původního svazku

**Comment by barinovak** [comment]
V současné chvíli při duplikaci svazku zůstavá v tabulce editace vstupních dat vyplněn metatitul, mutace, ročník, datum od a do, první a poslení číslo a poznámka. To by mohlo zůstat klidně stejné, i když označení mutace a vyplněná poznámka je podle mé zkušenosti zbytečná. Zpravidla tyto dvě položky stejně upravujeme.
V tabulce denních vydání zůstavají zatržené vybrané dny, to by mělo být zachováno a v tabulce detailní popis svazku se duplikuje vygenerovaná struktura, ale i se zatrženými defekty a je ponechán i status oveřeno, což by podle mého názoru být nemělo, ale na tom se musíme shodnout společně.

Můj návrh a téma k diskuzi:
Duplikaci svazku ponechat
tabulka Editace vstupních dat duplikovat jen metatitul, ročník, datum od do a číslo od do
tabulka denních vydání by se měla duplikovat tak, jak je
tabulka Detailní popis svazku by měla duplikovat jen vygenerovanou a upravenou strukturu bez zatržených defektů, poznámek a označení ověřeno

**Comment by AlesBrozek** [comment]
Jsem rozhodně pro možnost duplikace svazku (značně urychlí ukládání dalších svazků, které na sebe navazují), ale musí být funkční. V současnosti je nefunkční, jak to lze ilustrovat na fiktivním svazku 1013250901, který vznikl duplikací fiktivního svazku 1013250900. U tabulky Editace vstupních dat bych klidně umožnil duplikovat i mutační vydání a signaturu (zvláště kdy je dlouhá jako u NKP), protože pak lze mutační vydání a signaturu upravit formou změny v tabulce Editace vstupních dat.  U ostatního souhlasím s Kristýnou, předpokládám, že se budou duplikovat do tabulky Detailní popis svazku jen pravidelné přílohy a nikoliv "jiné přílohy"

**Comment by annavandasova** [comment]
@Kretiss udělat podle návrhu barinovak

**Comment by Kretiss** [comment]
@AlesBrozek Můžete prosím otestovat?

**Comment by AlesBrozek** [comment]
Duplikoval jsem svazek 1003250649 na dosud neukládaný (fiktivní) 1003250653. V podstatě duplikace funguje, ale vytvořil jsem ve svazku 1 chybějící číslo, které nemělo přílohu, a 1 číslo, u něhož příloha chyběla - viz printscreen. V Přehledu svazku by bylo ještě třeba, aby se uvedlo, že chybí příloha č. 42
![Snímek obrazovky 2024-10-13 v 15 00 09](https://github.com/user-attachments/assets/a981a429-192b-41b8-912f-edcc1ad4fcf3)
![Snímek obrazovky 2024-10-13 v 15 00 45](https://github.com/user-attachments/assets/f9fe7392-5e92-4866-a7d9-9a315e5e9bdb)

**Comment by Kretiss** [comment]
@AlesBrozek Upravil jsem ještě zobrazení chybějících čísel příloh v přehledu svazku. Zkontrolujte prosím, potom můžeme zavřít

**Comment by AlesBrozek** [comment]
Zkontrolováno, lze zavřít.
