### ISSUE TITLE
Nezobrazují se chybějící čísla

### ISSUE THREAD

**Issue by barinovak** [NLCR/evidence.periodik#244]
Nezobrazují se chybějící čísla, i když vyšla. Po zaškrtnutí pole "číslo chybí", zmizí tato informace z checkboxů okamžitě po uložení svazku a nezobrazí se pak ani v přehledu svazku jako chybějící číslo.
příklad Čsl. sport 1963, č.k. 265A004101
chybí č. 1, 3, 4. V detailním popisu svazku ani přehledu tato informace není.
![před uložením](https://github.com/NLCR/evidence.periodik/assets/40160250/0f9b3f36-1555-4350-8fc8-520aaccd8a5d)
![po uložení](https://github.com/NLCR/evidence.periodik/assets/40160250/9a984bca-2b18-42ba-9c5e-51ee588213db)
![přehled svazku](https://github.com/NLCR/evidence.periodik/assets/40160250/30553fb7-3bad-4aac-b95b-3915f3477f6f)

**Comment by AlesBrozek** [comment]
Hm, dnes (5.4.) jsem ukládal Čs. sport 1003250053, kde chyběla nějaká čísla, a teď vidím, že stále údaj o chybějících číslech mizí :-(
Doufám, že chybějící čísla znovu najdu jen kontrolou řady označující čísla výtisků...

**Comment by AlesBrozek** [comment]
Možná by se hodilo, kdyby údaj o chybějících číslech se uváděl i ve fasetách, takže bychom měli kontrolu, že PerMonik chybějící čísla registruje. Zdá se, že údaj o chybějících číslech zmizel i ze dříve uložených svazků :-(

**Comment by annavandasova** [comment]
@Kretiss prosím o opravu

**Comment by Kretiss** [comment]
Zobrazují se chybějící čísla podle zaškrtnutého políčka `číslo chybí`

**Comment by Kretiss** [comment]
@AlesBrozek @annavandasova Zavírám issue, v nové aplikaci jsme to vyladili. Pokud by se to mělo zobrazovat ve fasetách, založí se nové issue
