### ISSUE TITLE
mutační vydání - chyba zobrazení

### ISSUE THREAD

**Issue by frrezek** [NLCR/evidence.periodik#246]
Pokud chci změnit mutační vydání u ještě neuloženého svazku, otevře se nabídka u všech řádků, viz obrázek.

![Snímek obrazovky 2024-04-19 095255](https://github.com/NLCR/evidence.periodik/assets/40558340/66f3221c-a0bf-48e5-8bbc-1b6ac943e915)

**Comment by Kretiss** [comment]
Již opraveno v nové aplikaci
