### ISSUE TITLE
Chybí kontrola zapsání již jednou užitého čárového kódu svazku

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#247]
Při vytváření nového svazku aplikace nekontroluje, zda již existuje v Permoníku svazek s tímto čárovým kódem. Pokud vkládající nezkontroluje při editaci vstupních dat, zda už byl dříve zpracován svazek s určitým čárovým kódem, vyplní tabulku denních vydání a nechá vygenerovat svazek s již použitým čárovým kódem, dojde ke zdvojení řádků v detailním popisu svazku a k vyplnění hodnot v nových řádcích.

**Comment by annavandasova** [comment]
kontrola duplicity čk v rámci dané sigly

**Comment by Kretiss** [comment]
Již implementováno v nové aplikaci
