### ISSUE TITLE
Nelze zcela opravovat chybné období svazku

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#248]
![Snímek obrazovky 2024-06-02 v 18 16 20](https://github.com/NLCR/evidence.periodik/assets/141346237/b446a986-8871-4255-88e9-d898b50cd75d)
Dotaz na Československý sport z roku 1977 zobrazuje i výtisky NK ČR s čár.  kódem 1003250096, což je 1. kvartál roku 1978. K chybě došlo při zakládání svazku 1003250096, kdy jsem omylem nejprve napsal období 1.1.77 až 31.3.77 místo správného období 1.1.78 až 31.3.78. Po opravení na správné období by nemělo dojít k vzniku řádků, kdy je u sebe výtisk ze svazku 1003250092 a ze svazku 1003250096 (viz printscreen)

**Comment by AlesBrozek** [comment]
Navíc v přehledu svazku 1003250096 stále zůstává údaj Ročník 1977 89x, Data 01.01.77 - 31.3.78 !!!

**Comment by Kretiss** [comment]
@AlesBrozek Tady tedy smazat nějaký z uvedených svazků?

**Comment by AlesBrozek** [comment]
Psal jsem "Po opravení na správné období by nemělo dojít k vzniku řádků, kdy je u sebe výtisk ze svazku 1003250092 a ze svazku 1003250096" a upozorňoval na chybu u Editace vstupních dat, když se pracovalo se starou verzí. Předpokládám, že u badatelské aplikace jsou změny u Editace vstupních dat jinak řešeny a k tomuto problému nebude docházet (u badatelské verze se tento problém zatím neobjevil, tam byl jiný problém popsaný v issue 258). Takže bych později ručně opravil v ostré verzi data sám (smazáním a novým uložením), to bude jednodušší...

**Comment by Kretiss** [comment]
@AlesBrozek Takže tím pádem můžeme issue zavřít
