### ISSUE TITLE
Nelze vygenerovat nový svazek

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#249]
V testovacím Permoniku při vytváření nového svazku:
- datum od: nabízí současný měsíc, upravit na leden jako u staré aplikace
- datum do: zůstat v roce vyplněném v "datum od"
- bylo by dobré mít možnost Uložit svazek před Úpravou periodicity (jako u staré aplikace)
- u funkce Upravit periodicitu nelze vložit další vydání!!!
- po vygenerování svazku se objeví hláška Vstupní data jsou nesprávná (chyba validace) a svaek se nevygeneruje
- 
![Snímek obrazovky 2024-09-17 v 9 30 48](https://github.com/user-attachments/assets/83be54fb-b8fd-4625-8eea-332ec7a89370)
 
Na vstupní obrazovce a při výběru metatitulu nejsou názvy podle abecedy, Českosl. sport je na konci

**Comment by annavandasova** [comment]
- políčko "Přílohy na konci svazku" přesunout do tabulky periodicity 
- Název v Periodicitě předvyplnit z údaje metatilu; podnázev nepovinný, našeptává již použité údaje (jako ve staré aplikaci) 
- v tabulce Periodicity "Vložit další vydání" za Podnázev (jako ve staré aplikaci)

**Comment by Kretiss** [comment]
@AlesBrozek @annavandasova můžete otestovat

**Comment by AlesBrozek** [comment]
Vygenerovat nový svazek už jde, díky. V Údaji o svazku prosím ještě přesunout pole "První číslo" hned za pole "Datum od" (tak jak to bylo u staré aplikace, protože tyto údaje se opíší najednou z titulního listu periodika)

**Comment by Kretiss** [comment]
@AlesBrozek Upraveno
