### ISSUE TITLE
úprava Administrace

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#250]
- u Vlastníků změnit "Jméno" na "Zkratka" 
- u Metatilů změnit "Jméno" na "Náze" 
- u Publikace změnit "Publikace" na "Vydání"

**Comment by annavandasova** [comment]
@Kretiss pro vydání prosím zvolit "edition"

**Comment by Kretiss** [comment]
@annavandasova Prosím otestovat

**Comment by annavandasova** [comment]
v pořádku
