### ISSUE TITLE
Identifikace vlastníka dokumentu - sigla

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#251]
Pokud znám siglu vlastníka, je možné použít API na knihovny.cz (dokumentované na knihovny.cz/api

Např. pro siglu ABA010 je dotaz

https://www.knihovny.cz/api/v1/libraries/search?lookfor=ABA010&type=Sigla&sort=relevance&page=1&limit=20&prettyPrint=false&lng=cs

a vráti to 

{
  "resultCount": 1,
  "records": [
    {
      "sigla": "ABA010",
      "id": "library.000000010",
      "title": "Národní muzeum - Knihovna Národního muzea",
      "urls": []
    }
  ],
  "status": "OK"
}

Pak je možné použít to id (library.000000010) pro získání dalších informací ale pro naše potřeby asi stačí ten název.

**Comment by annavandasova** [comment]
doplnit i název instituce
do části vlevo doplnit sloupce (sigla, název?) - název TK zkusí a uvidíme

**Comment by Kretiss** [comment]
@annavandasova @zabak přidal jsem název, ale nebude se dát vyplňovat. Název se vyplní při uložení záznamu o vlastníkovi při kontrole sigly z atributu `title`

```
{
"sigla": "ABA010",
"id": "library.000000010",
"title": "Národní muzeum - Knihovna Národního muzea",
"urls": []
}
```

**Comment by annavandasova** [comment]
za mě takhle OK , co @zabak ?

**Comment by zabak** [comment]
za mě taky OK
