### ISSUE TITLE
chybějící čísla

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#252]
- v "Přehledu svazku" se nezobrazují zacheckboxované Chybějící čísla zakšrtnutá v Detailní popisu svazku 
- v Detailním popisu svazku nemizet Číslo chybějícího čísla

**Comment by AlesBrozek** [comment]
V "Přehledu svazku" se zobrazují zacheckboxované Chybějící čísla zakšrtnutá v Detailním popisu svazku a
v Detailním popisu svazku nemizí Číslo chybějícího čísla, ale **platí to jen v případě testovací aplikace**. V produkční to stále nefunguje. Bude se to řešit nebo už to necháme plavat a až se z testovací aplikace stane produkční, tak chybějící čísla doťukáme?

**Comment by Kretiss** [comment]
@AlesBrozek produkční aplikaci teď řešit nebudeme, nahradíme to novou

**Comment by annavandasova** [comment]
ok
