### ISSUE TITLE
přehled svazku

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#253]
- okénko "Přehled svazku" otevřít po kliknutí na čárový kód v Přehledové tabulce 
- do okénka "Přehled svazku" přidat tlačítka "Podrobný popis svazku" (jako ve staré aplikaci) 
- přidat do okénka tlačítko nebo křížek k uzavření

**Comment by AlesBrozek** [comment]
Za mne je to v pořádku
