### ISSUE TITLE
Funkce přečíslování pracuje chybně

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#254]
Pokud se použije přečíslování, funkce započte i existenci přílohy a u dalšího výtisku zvýší jeho číslo, takže na konci svazku už není správné č. 150, ale mnohem vyšší
![Snímek obrazovky 2024-10-10 v 9 35 44](https://github.com/user-attachments/assets/fbd65d85-5fc7-4488-b779-096a0e41734a)

**Comment by Kretiss** [comment]
@AlesBrozek Zkuste prosím znovu

**Comment by AlesBrozek** [comment]
Přečíslování už je v pořádku
