### ISSUE TITLE
Údaj o podnázvu se objeví jen u pondělních výtisků

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#255]
I když se u periodicity vyplní podnázev u všech dnů - viz 
![Snímek obrazovky 2024-10-10 v 21 30 20](https://github.com/user-attachments/assets/47ab97b1-1534-4b26-936c-b7362cd3c098)
objeví se jen u pondělních výtisků - viz 
![Snímek obrazovky 2024-10-10 v 21 31 03](https://github.com/user-attachments/assets/b243837f-85c9-495d-bc6b-afac48a8e88c)

**Comment by AlesBrozek** [comment]
a navíc se nepřenesl ani název pravidelné přílohy

**Comment by Kretiss** [comment]
@AlesBrozek Zkuste to prosím znovu, zkoušel jsem to teď u sebe a všechno mi normálně funguje.

<img width="1791" alt="Snímek obrazovky 2024-10-11 v 16 46 01" src="https://github.com/user-attachments/assets/b653d7ab-f9a2-4b6b-8d04-bf9ad407151b">
<img width="1794" alt="Snímek obrazovky 2024-10-11 v 16 46 08" src="https://github.com/user-attachments/assets/72251c45-0052-4e16-802b-379bc0f432b7">

**Comment by AlesBrozek** [comment]
Vytvořil jsem nový svazek a problém stále trvá - viz 
![Snímek obrazovky 2024-10-12 v 11 18 35](https://github.com/user-attachments/assets/50b65dc4-20cc-4452-81b1-197b20803ae6)

![Snímek obrazovky 2024-10-12 v 11 19 31](https://github.com/user-attachments/assets/993d2092-c4a1-41c7-b7b6-99d7e8c05b4c)

**Comment by Kretiss** [comment]
@AlesBrozek opraveno

**Comment by AlesBrozek** [comment]
v pořádku
