### ISSUE TITLE
Nelze vložit číslo přílohy, pokud vyšla v nepravidelný den

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#256]
Volno č. 52 nevyšlo 26.12., ale již 23.12.
![Snímek obrazovky 2024-10-10 v 21 47 30](https://github.com/user-attachments/assets/1e7ae9c7-0d33-435d-963e-ce9da35e361a)

**Comment by Kretiss** [comment]
@AlesBrozek zkuste teď prosím

**Comment by AlesBrozek** [comment]
Teď sice jde vytvořit přílohu, která vyšla o den dříve, tedy ve čtvrtek 9.7., ale nejde smazat příloha, která měla vyjít 10.7.

![Snímek obrazovky 2024-10-12 v 11 26 32](https://github.com/user-attachments/assets/f15e5eb2-cab4-48f8-847c-99a76a12d954)

**Comment by Kretiss** [comment]
@AlesBrozek chcete tu přílohu navíc úplně smazat jako celý řádek nebo chcete jen označit řádek že chybí (vyresetovat jestli je to příloha, typy poškození, mutaci atd)?

**Comment by AlesBrozek** [comment]
Zkusil jsem si to namodelovat v produkci a tam to vypadá takto (u chybějícího sobotního výtisku zůstalo č. 85, takže lze případně u chybějící pravidelné páteční přílohy taky nechat údaj, že to je č. přílohy 14)
![Snímek obrazovky 2024-10-13 v 16 24 46](https://github.com/user-attachments/assets/ba4fff93-f202-46a3-a25e-6af13a5be011)

**Comment by AlesBrozek** [comment]
Teď jsem si uvědomil, že jsem Vám v předchozím commentu namodeloval méně běžný případ, kdy příloha chyběla, protože se v knihovně ztratila nebo jí nebyla dodána (a v tom případě by určitě mělo zůstat číslo přílohy 14 a zbytek řádku by byl prázdný podobně jako u chybějícího čísla 85). Když jsem před několika dny psal "Teď sice jde vytvořit přílohu, která vyšla o den dříve, tedy ve čtvrtek 9.7., ale nejde smazat příloha, která měla vyjít 10.7.", tak se jednalo o častý případ, kdy příloha nechybí, ale vyšla místo v pátek v jiný den. Pak to v produkci vždy vypadalo - viz printscreen (tedy č. 51 vyšlo 23.12.85, č. 52 vyšlo 29.12.85), v testovací badatelské aplikaci nešlo vymazat č. 52 u pátečního čísla z 27.12., kdy u výtisku z toho dne nechyběla příloha z důvodu, že by to byla ztráta, ale z důvodu, že vyšla až  29.12.85.
![Snímek obrazovky 2024-10-13 v 16 38 49](https://github.com/user-attachments/assets/6f985887-e14a-4799-a026-3b5c416110e4)
