### ISSUE TITLE
Přehled svazku uvádí nesprávné údaje

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#257]
Dosud (ve staré aplikaci) se uvádělo v Přehledu svazku:
čísla 40-308
V nové aplikaci čísla -307
Ideální by bylo uvést: čísla 231-307, pravidelné přílohy č. 40-52 (a jedna pravid. příloha nečíslovaná)

**Comment by AlesBrozek** [comment]
Je to vidět na printscreenech:
![Snímek obrazovky 2024-10-10 v 22 30 03](https://github.com/user-attachments/assets/7be65a4b-f529-4ebd-8595-d2cfcce897f5)
![Uploading Snímek obrazovky 2024-10-10 v 22.27.36.png…]()

**Comment by AlesBrozek** [comment]
![Snímek obrazovky 2024-10-10 v 22 27 36](https://github.com/user-attachments/assets/7cd7d6a3-de35-47cf-9d75-dafc94430f5e)

**Comment by AlesBrozek** [comment]
Chybějící čísla uvádí formou datumu, kdy měla vyjít. Pokud chybí pravidelná příloha a výtisk je ve svazku bez přílohy, bude se to asi muset uvést do poznámky, protože se z datumu nepozná, zda je chybějící příloha nebo celý výtisk

**Comment by Kretiss** [comment]
@AlesBrozek Máte prosím nějaký příklad, který existuje na produkci i testu? Přehrával jsem databázi kvůli změně datového modelu a tento svazek na testu nevidím. Hádám že jste s ním zkoušel testovat aplikaci a vytvářel jste ho ručně. Děkuji

**Comment by Kretiss** [comment]
@AlesBrozek dal jsem na test data co byly na produkci, zobrazuje se to správně

https://permonik-test.nkp.cz/cs/volume/f91e85f7-ecbf-486c-975d-53cdb3e25a82?backMetaTitleId=50b82e20-a61d-4f9b-9873-46479ab66960&jumpToSpecimenWithId=d193d8a4-8b65-4745-960d-329b557c3e9a

Dokážete zreplikovat jak jste svazek generoval?

**Comment by AlesBrozek** [comment]
Svazek s čár. kódem 1003250649 jsem vytvořil v badatelské aplikaci podle údajů ve staré aplikaci (snad jen bez poznámek o nekvalitním tisku, abych si usnadnil práci) a zvolil jej z toho důvodu, protože jsem odzkušoval, zda se v badatelské aplikaci snadno upraví dny na konci roku, kdy noviny vycházely nepravidelně.Nyní, když jste přepsal badatelskou aplikaci ostrými daty, snáze porovnáme údaje v Přehledu svazku ve staré a nové aplikaci. Takže, jak ukazuje printscreen, v nové aplikaci se správně uvádí č. 231-308, ve staré aplikaci chybně 40-308 . Bude třeba, aby se NLCR vyjádřila, co vše a v jaké podobě by mělo být nyní, kdy už máme více zkušeností, v badatelské aplikaci.
![Snímek obrazovky 2024-10-12 v 12 02 29](https://github.com/user-attachments/assets/8b078674-a8c0-423a-a2fb-b71c2af59d7b)
![Snímek obrazovky 2024-10-12 v 12 02 11](https://github.com/user-attachments/assets/da9fd140-8df0-4c8b-9b5d-6e459d61be24)

**Comment by AlesBrozek** [comment]
Bohužel však u svazků, které byly uloženy ve staré aplikaci, se po přehrání databáze kvůli změně datového modelu objevuje rozdíl v údaji o číslech v Přehledu svazku u staré aplikace a u badatelské aplikace, např. u svazku  1003250617, kde je údaj o číslech správný jen ve staré aplikaci, viz printscreen (navíc je rozdíl i u Fyzického stavu: podle staré aplikace je stav "poškozený", podle badatelské aplikace je stav "vyhovující")
![Snímek obrazovky 2024-10-12 v 17 08 29](https://github.com/user-attachments/assets/ef1a4794-dda6-4695-9122-ddc870d9b925)
![Snímek obrazovky 2024-10-12 v 17 08 35](https://github.com/user-attachments/assets/e3c20a9c-06d5-48b7-bc7f-a2143508aed7)

**Comment by AlesBrozek** [comment]
A ještě připojuji printscreen, který ukazuje, že ve staré aplikaci se v Přehledu svazku neuvádělo jen datum chybějícího čísla, ale i jeho číslo na rozdíl od testované aplikace (a bylo by vhodné, aby tento údaj (datum chybějícího čísla) se dostal i mezi fasety vzhledem k jeho důležitosti)

![Snímek obrazovky 2024-10-12 v 18 24 21](https://github.com/user-attachments/assets/34ff7638-72c4-480c-87ae-92713b8bf950)
![Snímek obrazovky 2024-10-12 v 18 24 32](https://github.com/user-attachments/assets/d3b9d812-a634-40c2-8495-59333aa299bb)

**Comment by Kretiss** [comment]
@AlesBrozek prosím o otestování, mělo by být opraveno. Rosah čísel se musí počítat v aplikaci a ne v solru, protože u některých čísel a čísel příloh nejsou vyplněny čísla, to znamená, že je tam prázdná hodnota. Solr potom počítá data chybně.

**Comment by AlesBrozek** [comment]
Porovnal jsem se starou aplikací a vypadá to relativně dobře (ještě je nutné řešit ten méně běžný případ chybějících pravidelných příloh v issue #241). Co znamená Čísla příloh: Infinity - -Infinity (např. u svazku 1003250030) a Čísla příloh: NaN - NaN (u sv. 2619910475)? Nelze nahradit něčím srozumitelnějším pro běžného uživatele? 
Ještě přemýšlím, proč u sv. 2619910475 je ve staré aplikaci uvedeno 132 mutač. vydání, zatímco v testovací jen 131 vydání. Předpokládal jsem, že jste do test. aplikace přetáhl všechna data z produkce, takže se mi nezdá, že by od té doby někdo něco dělal v produkci se svazkem 2619910475

**Comment by Kretiss** [comment]
@AlesBrozek Ty hodnoty NaN a Infinity byly kvůli tomu, že některé svazky mají číslo třeba 51a, 51b a to se nedá konvertovat na číslo. Ošetřil jsem. 131 vydání v nové aplikaci je proto, protože nová aplikace do těch hodnot nezapočítává údaje z chybějících čísel jako ta stará.

**Comment by Kretiss** [comment]
@AlesBrozek Pokud je to takhle v pořádku, dejte mi prosím vědět, ať můžeme issue zavřít

**Comment by AlesBrozek** [comment]
v pořádku
