### ISSUE TITLE
Nejsou vidět detaily o všech exemplářích

### ISSUE THREAD

**Issue by AlesBrozek** [NLCR/evidence.periodik#261]
3.1.53 bych měl vidět 3 exempláře, ale vidím detaily jen o 1,5 exempláři, dál nedokáži na notebooku posunout...
![Snímek obrazovky 2024-10-14 v 15 04 09](https://github.com/user-attachments/assets/ca3564b6-acf1-4d60-87ff-a0453d56469d)
![Snímek obrazovky 2024-10-14 v 14 42 18](https://github.com/user-attachments/assets/dfeac6c5-f706-45d9-8ca2-de525fe314a1)

**Comment by Kretiss** [comment]
@AlesBrozek opraveno

**Comment by AlesBrozek** [comment]
Funguje, lze zavřít
