### ISSUE TITLE
doplnit do UI zobrazení data poslední aktualizace

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#262]
Viz #240: 

- [ ] Na vhodném místě zobrazovat datum poslední aktualizace (stačí pro knihovníky).
- [ ] Pokud datum chybí u existujících starších dat, doplnit ho.

**Comment by Kretiss** [comment]
Přidat doprava nahoru do detailního popisu svazku spolu s počtem řádků (skrýt patičku tabulky)

**Comment by Kretiss** [comment]
@zabak prosím otestovat

**Comment by Kretiss** [comment]
v pořádku
