### ISSUE TITLE
Názvy

### ISSUE THREAD

**Issue by annavandasova** [NLCR/evidence.periodik#263]
@Kretiss prosím změnit:
Údaje o svazku -> Editace vstupních dat
Popis svazku -> Detailní popis svazku
Periodicita -> Tabulka denních vydání

**Comment by Kretiss** [comment]
@annavandasova prosím otestovat

**Comment by annavandasova** [comment]
@Kretiss tu Tab. denních vydání bych klidně rozepsala na Tabulku denních vydání, místo tam na to je :)

**Comment by Kretiss** [comment]
@annavandasova upraveno

**Comment by AlesBrozek** [comment]
v pořádku
