### ISSUE TITLE
prihlaseni

### ISSUE THREAD

**Issue by Chlupova** [NLCR/evidence.periodik#28]
Na heslo test se nelze v MZK prihlasit

**Comment by Chlupova** [comment]
ano take TEST

Dne 27.08.2018 10:21, Alberto Hernandez napsal:

**Comment by albertoh** [comment]
male pismena, prosim

**Comment by Chlupova** [comment]
diky, uz jsem se prihlasila.

Dne 27.08.2018 11:48, Alberto Hernandez napsal:

**Comment by ludvicekj** [comment]
s přihlášením jsme taktéž zaznamenali potíže. i při zadání správných údajů, aplikace vůbec nereaguje a nepřihlásí se. 
občas pomůže zadání špatných, aplikace ohlásí "Špatné přihlašovací údaje.", následně po zadání správných se přihlásí.

**Comment by ludvicekj** [comment]
zjistili jsme, že přihlášení funguje při zadání údajů a stisku klávesy Enter, ale ne při kliknutí myši na tlačítko Přihlásit.

**Comment by ludvicekj** [comment]
funguje přes Enter i kliknutí myší.
