### ISSUE TITLE
nabidka vydání

### ISSUE THREAD

**Issue by Chlupova** [NLCR/evidence.periodik#35]
do nabídky "Duplikovat výtisk v novém vydání" přidat k ranní a odpolední i polední

**Comment by barinovak** [comment]
přidat i nedělní vydání

**Comment by korhon** [comment]
Není polední vydání totéž co odpolední?

**Comment by Chlupova** [comment]
Je, ale v novinach je popsano jako poledni...

Dne 05.09.2018 09:15, korhon napsal:

**Comment by albertoh** [comment]
Pridano
