### ISSUE TITLE
skloňování u labelů na hlavní stránce

### ISSUE THREAD

**Issue by zabak** [NLCR/evidence.periodik#77]
1 mutací
2 mutací
3 mutací
4 mutací
... není česky. To samé u vlastníků, záznamů a exemplářů. Je to na hlavní stránce, tak ať to není úplně na první pohled trapné, že knihovna neumí česky.

**Comment by pavelkocourek** [comment]
Změnit v boxu na 

- Záznamy: 1
- Vlastníci: 4
- Exempláře: 2
- Mutace: 1

aby to bylo správně

**Comment by pavelkocourek** [comment]
+ formát data na úvodní stránce na 01.01.2011, jako je ve zbytku aplikace

**Comment by zabak** [comment]
Prosím o textaci podle toho co píše výše Pavel Kocourek.

**Comment by annavandasova** [comment]
hotovo -> produkce
